/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.BancoDAO;

import dao.BancoMovimentoDAO;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
//import java.math.BigInteger;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Banco;

import model.BancoMovimento;
//import org.hibernate.cfg.annotations.reflection.XMLContext;
import util.JTableFonteColunaDireitaAzul;
import util.JTableFonteColunaDireitaVermelha;

/**
 *
 * @author root
 */
public class BancoMovimentoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BancoMovimentoView
     */
    public static List<Banco> listBanco; 
    List<BancoMovimento> listBancoMov;
    BancoMovimento bancoMov;
    BancoMovimentoDAO bancoMovDAO;
    public static DefaultTableModel amodel;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    int ultimoRegistro = 0;
    public BancoMovimentoView() {
        initComponents();
        carregaCombobox();
    }

    
    
    
    
    
    
    
    
    public static void carregaCombobox(){      
        BancoDAO bancoDAO = new BancoDAO();
        listBanco = bancoDAO.listBanco();       
     
        jcbBanco.removeAllItems();
        for (Banco banco : listBanco){
            jcbBanco.addItem(banco.getDescricao());
        }
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbBanco = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCredito = new javax.swing.JTextField();
        jtfObservacao = new javax.swing.JTextField();
        jbtSalvar = new javax.swing.JButton();
        jftDtLancamento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtSair = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtTransferencia = new javax.swing.JButton();
        jbtExcluirLanc = new javax.swing.JButton();
        jbtImprimir = new javax.swing.JButton();

        setMaximizable(true);
        setTitle("Movimento Conta Banco");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SELECIONE O BANCO"));

        jcbBanco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbBancoFocusLost(evt);
            }
        });
        jcbBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbBancoKeyPressed(evt);
            }
        });

        jLabel1.setText("CONTA BANCO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("HISTÓRICO MOVIMENTAÇÃO"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA LANÇAMENTO", "R$ CRÉDITO", "R$ DEBITO", "R$ SALDO", "HISTÓRICO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(350);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("LANÇAR CREDITO CONTA BANCO"));

        jLabel2.setText("CRÉDITO");

        jLabel3.setText("HISTÓRICO");

        jtfCredito.setEnabled(false);
        jtfCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCreditoKeyPressed(evt);
            }
        });

        jtfObservacao.setEnabled(false);
        jtfObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfObservacaoKeyPressed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jbtSalvar.setText("OK");
        jbtSalvar.setEnabled(false);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        try {
            jftDtLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDtLancamento.setEnabled(false);
        jftDtLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftDtLancamentoKeyPressed(evt);
            }
        });

        jLabel4.setText("DATA LANÇAMENTO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jftDtLancamento))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtfObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvar)
                    .addComponent(jftDtLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jbtSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSairKeyPressed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });
        jbtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtCancelarKeyPressed(evt);
            }
        });

        jbtTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sync.png"))); // NOI18N
        jbtTransferencia.setText("Transferência");
        jbtTransferencia.setEnabled(false);
        jbtTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTransferenciaActionPerformed(evt);
            }
        });
        jbtTransferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtTransferenciaKeyPressed(evt);
            }
        });

        jbtExcluirLanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbtExcluirLanc.setText("Excluir Lançamento");
        jbtExcluirLanc.setEnabled(false);
        jbtExcluirLanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirLancActionPerformed(evt);
            }
        });

        jbtImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print-icon.png"))); // NOI18N
        jbtImprimir.setText("Imprimir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jbtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluirLanc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtCancelar)
                .addComponent(jbtTransferencia)
                .addComponent(jbtExcluirLanc)
                .addComponent(jbtImprimir))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jcbBancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbBancoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            
            carregaTable(listBanco.get(jcbBanco.getSelectedIndex()));
            
            jtfCredito.setEnabled(true);
            jftDtLancamento.setEnabled(true);
            jtfObservacao.setEnabled(true);
            jbtSalvar.setEnabled(true);
            
            if (!listBanco.get(jcbBanco.getSelectedIndex()).getBancoMovimentoList().isEmpty())
               jbtTransferencia.setEnabled(true);
            
            
            jcbBanco.setEnabled(false);
            jftDtLancamento.requestFocus();
        }
    }//GEN-LAST:event_jcbBancoKeyPressed

    private void jtfCreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCreditoKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER){
            jtfObservacao.requestFocus();           
        }
    }//GEN-LAST:event_jtfCreditoKeyPressed

    private void jtfObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfObservacaoKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER){
           jbtSalvar.requestFocus();           
        }
    }//GEN-LAST:event_jtfObservacaoKeyPressed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
       if (!jtfCredito.getText().equals("")){
           bancoMov = new BancoMovimento();
           bancoMovDAO = new BancoMovimentoDAO();
           
           String creditoStr = null;
           String saldoStr = null;
           float saldo = 0, credito= 0; 
           int ultimoRegistro = 0;
           
           creditoStr = jtfCredito.getText();
           creditoStr = creditoStr.replace(".", "");
           creditoStr = creditoStr.replace(",", ".");           
           credito = Float.parseFloat(creditoStr);
           
           if ((jTable1.getRowCount()-1) < 0){
               saldoStr = "0";
           }else{        
               ultimoRegistro = jTable1.getRowCount() - 1;
               saldoStr = amodel.getValueAt(ultimoRegistro, 3).toString();
           }
           saldo = Float.parseFloat(saldoStr);
           
           saldo = (saldo + credito);
           
           
                  
           
         // String sdo = bancoMovDAO.saldoAtual(listBanco.get(jcbBanco.getSelectedIndex()));
           
           
           
           //Salvar Dados Banco Movimento.
           bancoMov.setIdBanco(listBanco.get(jcbBanco.getSelectedIndex()));
           try {
               bancoMov.setDtLancamento(sdf.parse(jftDtLancamento.getText()));
           } catch (ParseException ex) {
               JOptionPane.showMessageDialog(null, "Erro Data Lançamento. Error: "+ex.getMessage());
           }
           bancoMov.setVlEntrada(new BigDecimal(creditoStr));
           bancoMov.setSaldo(new BigDecimal(saldo));
           bancoMov.setObs(jtfObservacao.getText());
           
           bancoMovDAO.salvar(bancoMov);
           
           

           
           
           
           //JOptionPane.showMessageDialog(null, "Credito Adicionado Com Sucesso !!!");
           
           int index = jcbBanco.getSelectedIndex();
           carregaCombobox();
           carregaTable(listBanco.get(index));
           jcbBanco.setSelectedIndex(index);
           limpar();
           jftDtLancamento.requestFocus();
           
       }else{
           JOptionPane.showMessageDialog(null, "Digite um Valor no Crédito!!!");
           return;
       }
           
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jftDtLancamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftDtLancamentoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            jtfCredito.requestFocus();           
        }
       
    }//GEN-LAST:event_jftDtLancamentoKeyPressed

    private void jcbBancoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbBancoFocusLost

        
    }//GEN-LAST:event_jcbBancoFocusLost

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed

        amodel.setNumRows(0);
        jtfCredito.setEnabled(false);
        jftDtLancamento.setEnabled(false);
        jtfObservacao.setEnabled(false);
        jcbBanco.setEnabled(true);
        jbtSalvar.setEnabled(false);
        jftDtLancamento.setText("");
        jbtTransferencia.setEnabled(false);
        
        
        jcbBanco.requestFocus();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTransferenciaActionPerformed

       TransferenciaView trans = new TransferenciaView(new java.awt.Frame(), true);
        trans.setTitle("Transferência de Saldo de Conta ");
        trans.setLocationRelativeTo(null); // centraliza a tela
        
        trans.jlConta.setText(jcbBanco.getSelectedItem().toString());
        
        //Pegar o saldo
        int ultimoRegistro = 0; String saldoStr = null;
        if ((jTable1.getRowCount()-1) < 0){
               saldoStr = "0";
           }else{        
               ultimoRegistro = jTable1.getRowCount() - 1;
               saldoStr = amodel.getValueAt(ultimoRegistro, 3).toString();
           }        
        trans.jlSaldo.setText(saldoStr);
        trans.setVisible(true);
        
        String conta = jcbBanco.getSelectedItem().toString();
        carregaCombobox();
        jcbBanco.setSelectedItem(conta);
        carregaTable(listBanco.get(jcbBanco.getSelectedIndex()));
    }//GEN-LAST:event_jbtTransferenciaActionPerformed

    private void jbtTransferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtTransferenciaKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               //jButton2ActionPerformed(null);
                jbtTransferenciaActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtTransferenciaKeyPressed

    private void jbtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtCancelarKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
                jbtCancelarActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtCancelarKeyPressed

    private void jbtSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSairKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtSairActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtSairKeyPressed

    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtSalvarActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        
        
        ultimoRegistro = listBanco.get(jcbBanco.getSelectedIndex()).getBancoMovimentoList().size();
        ultimoRegistro = (ultimoRegistro - 1);     
        
        if ((jTable1.getSelectedRow()) == ultimoRegistro)
            jbtExcluirLanc.setEnabled(true);
        else
            jbtExcluirLanc.setEnabled(false);      
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtExcluirLancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirLancActionPerformed
        bancoMov= new BancoMovimento();
        BancoMovimento bancoMovPenultimo = new BancoMovimento();
        bancoMovDAO = new BancoMovimentoDAO();
      
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir este lançamento?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
           bancoMov = listBanco.get(jcbBanco.getSelectedIndex()).getBancoMovimentoList().get(ultimoRegistro);
           //Exclui o últimor Registro.
           bancoMovDAO.excluir(bancoMov);
       
           String conta = jcbBanco.getSelectedItem().toString();
           carregaCombobox();
           jcbBanco.setSelectedItem(conta);
           carregaTable(listBanco.get(jcbBanco.getSelectedIndex()));
                  
        }
        jbtExcluirLanc.setEnabled(false);
        jftDtLancamento.requestFocus();  
        
        
        
    }//GEN-LAST:event_jbtExcluirLancActionPerformed

    
    public void limpar(){
        jtfCredito.setText("");
        jtfObservacao.setText("");
        jftDtLancamento.setText("");
    }
    
    public void carregaTable(Banco banco){
        
        amodel = (DefaultTableModel) jTable1.getModel();
        amodel.setNumRows(0);
        
        float saldo = 0;
     
        for(BancoMovimento bm : banco.getBancoMovimentoList()){           
           amodel.addRow(new Object[]{sdf.format(bm.getDtLancamento()), bm.getVlEntrada(), bm.getVlSaida(), bm.getSaldo(), bm.getObs()});                
        }      
        
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new JTableFonteColunaDireitaAzul());    
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new JTableFonteColunaDireitaVermelha());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new JTableFonteColunaDireitaAzul());            
     
      //Pegando o último Registro.
      //Muda cor da Linha Selecionada na Jtable1.
        jTable1.setSelectionBackground( new Color(255,230,22) );
            //Altera cor da Fonte na linha selecionada.          
        jTable1.setSelectionForeground(Color.BLACK);
        
        
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtExcluirLanc;
    private javax.swing.JButton jbtImprimir;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JButton jbtTransferencia;
    public static javax.swing.JComboBox<String> jcbBanco;
    private javax.swing.JFormattedTextField jftDtLancamento;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfObservacao;
    // End of variables declaration//GEN-END:variables
}
