/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.BancoDAO;
import dao.BancoMovimentoDAO;
import dao.CaixaDAO;
import dao.CaixaItensDAO;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Banco;
import model.BancoMovimento;
import model.CaixaItens;
import static movimentoView.CaixaView.caixa;
import static movimentoView.CaixaView.jTable1;
import util.JTableFonteColunaDireitaAzul;
import util.JTableFonteColunaDireitaVermelha;

/**
 *
 * @author del
 */
public class CaixaLancamentoView extends javax.swing.JDialog {

    /**
     * Creates new form CaixaLancamentoView
     */
    
    GregorianCalendar calendar = new GregorianCalendar();
    SimpleDateFormat formatadorHD = new SimpleDateFormat("dd/MM/yyyy' - 'HH':'mm");
    Locale locale = new Locale("pt", "BR");
    DefaultTableModel amodel = (DefaultTableModel) CaixaView.jTable1.getModel(); 
    
    private Banco banco;
    private BancoDAO daoBanco;
    List<Banco> listaBanco;
    public CaixaLancamentoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jcbBanco.setVisible(false);
        jLabel3.setVisible(false);
        jrbDinheiro.requestFocus();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbDinheiro = new javax.swing.JRadioButton();
        jrbCheque = new javax.swing.JRadioButton();
        jrbCartaoDebito = new javax.swing.JRadioButton();
        jrbCartaoCredito = new javax.swing.JRadioButton();
        jrbValeAlimentacao = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jrbSaidaSangria = new javax.swing.JRadioButton();
        jrbSaidaPagto = new javax.swing.JRadioButton();
        jrbEntrada = new javax.swing.JRadioButton();
        jrbSaidaTransferencia = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jbtSalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jtfValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfObs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbBanco = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lançamentos Entrada / Saída ");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo do Lançamento"));

        buttonGroup1.add(jrbDinheiro);
        jrbDinheiro.setText("Dinheiro");
        jrbDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDinheiroActionPerformed(evt);
            }
        });
        jrbDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbDinheiroKeyPressed(evt);
            }
        });

        buttonGroup1.add(jrbCheque);
        jrbCheque.setText("Cheque");
        jrbCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbChequeActionPerformed(evt);
            }
        });
        jrbCheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbChequeKeyPressed(evt);
            }
        });

        buttonGroup1.add(jrbCartaoDebito);
        jrbCartaoDebito.setText("Cartão Débito");
        jrbCartaoDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCartaoDebitoActionPerformed(evt);
            }
        });
        jrbCartaoDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbCartaoDebitoKeyPressed(evt);
            }
        });

        buttonGroup1.add(jrbCartaoCredito);
        jrbCartaoCredito.setText("Cartão Crédito");
        jrbCartaoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCartaoCreditoActionPerformed(evt);
            }
        });
        jrbCartaoCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbCartaoCreditoKeyPressed(evt);
            }
        });

        buttonGroup1.add(jrbValeAlimentacao);
        jrbValeAlimentacao.setText("Vale Alimentação");
        jrbValeAlimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbValeAlimentacaoActionPerformed(evt);
            }
        });
        jrbValeAlimentacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbValeAlimentacaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbDinheiro)
                .addGap(18, 18, 18)
                .addComponent(jrbCartaoDebito)
                .addGap(18, 18, 18)
                .addComponent(jrbCartaoCredito)
                .addGap(18, 18, 18)
                .addComponent(jrbCheque)
                .addGap(18, 18, 18)
                .addComponent(jrbValeAlimentacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDinheiro)
                    .addComponent(jrbCheque)
                    .addComponent(jrbCartaoDebito)
                    .addComponent(jrbCartaoCredito)
                    .addComponent(jrbValeAlimentacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo da Operação"));

        buttonGroup2.add(jrbSaidaSangria);
        jrbSaidaSangria.setText("Saída - Sangria");
        jrbSaidaSangria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSaidaSangriaActionPerformed(evt);
            }
        });
        jrbSaidaSangria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbSaidaSangriaKeyPressed(evt);
            }
        });

        buttonGroup2.add(jrbSaidaPagto);
        jrbSaidaPagto.setText("Saída - Pagamento de despesas");
        jrbSaidaPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSaidaPagtoActionPerformed(evt);
            }
        });
        jrbSaidaPagto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbSaidaPagtoKeyPressed(evt);
            }
        });

        buttonGroup2.add(jrbEntrada);
        jrbEntrada.setText("Entrada - Acréscimo");
        jrbEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEntradaActionPerformed(evt);
            }
        });
        jrbEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbEntradaKeyPressed(evt);
            }
        });

        buttonGroup2.add(jrbSaidaTransferencia);
        jrbSaidaTransferencia.setText("Saída - Transferência de Saldo");
        jrbSaidaTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSaidaTransferenciaActionPerformed(evt);
            }
        });
        jrbSaidaTransferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbSaidaTransferenciaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jrbSaidaSangria)
                        .addGap(178, 178, 178)
                        .addComponent(jrbSaidaTransferencia))
                    .addComponent(jrbSaidaPagto)
                    .addComponent(jrbEntrada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbSaidaSangria)
                    .addComponent(jrbSaidaTransferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSaidaPagto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbEntrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setEnabled(false);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Operação"));

        jtfValor.setBackground(new java.awt.Color(248, 241, 120));
        jtfValor.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jtfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorKeyPressed(evt);
            }
        });

        jLabel2.setText("OBSERVAÇÃO");

        jtfObs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfObsFocusLost(evt);
            }
        });
        jtfObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfObsKeyPressed(evt);
            }
        });

        jLabel1.setText("R$ - VALOR");

        jcbBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbBancoKeyPressed(evt);
            }
        });

        jLabel3.setText("CONTA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel2)
                    .addComponent(jtfObs, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEntradaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jrbDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbDinheiroKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbDinheiro.isSelected()){
                jtfValor.setText(CaixaView.jtfSaldoDinheiro.getText());
                jrbSaidaSangria.requestFocus();
            }else
                jrbCartaoDebito.requestFocus();
        }
    }//GEN-LAST:event_jrbDinheiroKeyPressed

    private void jrbChequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbChequeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbCheque.isSelected()){
                jtfValor.setText(CaixaView.jtfSaldoCheque.getText());
                jrbSaidaTransferencia.requestFocus();
            }else
                jrbValeAlimentacao.requestFocus();
        }
    }//GEN-LAST:event_jrbChequeKeyPressed

    private void jrbSaidaSangriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbSaidaSangriaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
//            String op = System.getProperty("os.name");
//            if (!"Linux".equals(op)){
               if (jrbSaidaSangria.isSelected()){
                   jLabel3.setVisible(false);
                   jcbBanco.setVisible(false);                
                   jtfValor.requestFocus();
                }else
                     jrbSaidaPagto.requestFocus();
          //  }
        }
    }//GEN-LAST:event_jrbSaidaSangriaKeyPressed

    private void jrbSaidaPagtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbSaidaPagtoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbSaidaPagto.isSelected()){
               jLabel3.setVisible(false);
               jcbBanco.setVisible(false);        
                jtfValor.requestFocus();
            }else
                jrbEntrada.requestFocus();
        }
    }//GEN-LAST:event_jrbSaidaPagtoKeyPressed

    private void jrbEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbEntradaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbEntrada.isSelected())
                jtfValor.requestFocus();
            else
                jrbSaidaTransferencia.requestFocus();
        }
    }//GEN-LAST:event_jrbEntradaKeyPressed

    private void jtfValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfValor.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Digite um Valor R$ !!!");
            }else{
                String valor = jtfValor.getText();
                valor = valor.replace(".", "");
                valor = valor.replace(",", ".");
                jtfValor.setText(new DecimalFormat("#,##0.00").format(Float.parseFloat(valor)));
                jtfObs.requestFocus();
            }
        }
    }//GEN-LAST:event_jtfValorKeyPressed

    private void jtfObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfObsKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
           jbtSalvar.setEnabled(true);
           jbtSalvar.requestFocus();
        }
    }//GEN-LAST:event_jtfObsKeyPressed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
            
        
        CaixaDAO caixaDAO = new CaixaDAO();
        CaixaItensDAO itensCaixaDAO = new CaixaItensDAO();
        CaixaItens itensCaixa = new CaixaItens();
        
        //Campos da Jtable Caixa.
        String dataHora = (formatadorHD.format(calendar.getTime()));
        String descricao = null;
        String entrada = null;
        String saida = null;
        String obs = null;
        String formaPagto = null;
        int id = 0;
        
        
        if (jrbDinheiro.isSelected()){
            formaPagto = "DINHEIRO";
        }else 
            if (jrbCheque.isSelected()){
                formaPagto = "CHEQUE";
            }else
                if (jrbCartaoCredito.isSelected())
                    formaPagto = "CARTAO CREDITO";
                else
                    if (jrbCartaoDebito.isSelected())
                        formaPagto = "CARTAO DEBITO";
                    else
                        if (jrbValeAlimentacao.isSelected())
                            formaPagto = "VALE ALIMENTACAO";
                        else{
                            JOptionPane.showMessageDialog(null, "SELECIONE UMA FORMA DE PAGAMENTO/RECEBIMENTO");
                            return;                        
                        }    
                         
        
        if (jrbSaidaSangria.isSelected() || jrbSaidaPagto.isSelected() || jrbSaidaTransferencia.isSelected()){           
           if (jrbSaidaSangria.isSelected()) 
              descricao = "SAIDA - SANGRIA";
           else
               if (jrbSaidaPagto.isSelected())
                   descricao = "SAIDA - DESPESA";
                else
                   if (jrbSaidaTransferencia.isSelected())
                       descricao = "TRANSFERENCIA DE SALDO P/ CONTA ("+jcbBanco.getSelectedItem().toString()+")";
           
           saida = jtfValor.getText();
           saida = saida.replace(".", "");
           saida = saida.replace(",", ".");
           entrada = "";           
           
                
            //Coloca Fonte a Direita na cor Vermelha
            jTable1.getColumnModel().getColumn(3).setCellRenderer(new JTableFonteColunaDireitaVermelha()); 
                
            if (jrbDinheiro.isSelected()){
               CaixaView.caixa.setDinheiroSaida(CaixaView.caixa.getDinheiroSaida().add(new BigDecimal(saida)));
               CaixaView.caixa.setTotalSaida(CaixaView.caixa.getTotalSaida().add(new BigDecimal(saida)));
               CaixaView.caixa.setSaldoDinheiro(CaixaView.caixa.getSaldoDinheiro().subtract(new BigDecimal(saida)));             
               CaixaView.caixa.setSaldoFinal(CaixaView.caixa.getSaldoFinal().subtract(new BigDecimal(saida)));                               
            }else
                if (jrbCheque.isSelected()){
                   CaixaView.caixa.setChequeSaida(CaixaView.caixa.getChequeSaida().add(new BigDecimal(saida)));
                   CaixaView.caixa.setTotalSaida(CaixaView.caixa.getTotalSaida().add(new BigDecimal(saida)));
                   CaixaView.caixa.setSaldoCheque(CaixaView.caixa.getSaldoCheque().subtract(new BigDecimal(saida)));
                   CaixaView.caixa.setSaldoFinal(CaixaView.caixa.getSaldoFinal().subtract(new BigDecimal(saida)));                               
                }else
                    if (jrbCartaoDebito.isSelected()){
                       CaixaView.caixa.setCartaoDebitoSaida(CaixaView.caixa.getCartaoDebitoSaida().add(new BigDecimal(saida)));
                       CaixaView.caixa.setTotalSaida(CaixaView.caixa.getTotalSaida().add(new BigDecimal(saida)));
                       CaixaView.caixa.setSaldoCartaoDebito(CaixaView.caixa.getSaldoCartaoDebito().subtract(new BigDecimal(saida)));
                       CaixaView.caixa.setSaldoFinal(CaixaView.caixa.getSaldoFinal().subtract(new BigDecimal(saida))); 
                    }else
                        if (jrbCartaoCredito.isSelected()){                             
                           CaixaView.caixa.setCartaoCreditoSaida(CaixaView.caixa.getCartaoCreditoSaida().add(new BigDecimal(saida)));                             
                           CaixaView.caixa.setTotalSaida(CaixaView.caixa.getTotalSaida().add(new BigDecimal(saida)));
                           CaixaView.caixa.setSaldoCartaoCredito(CaixaView.caixa.getSaldoCartaoCredito().subtract(new BigDecimal(saida)));
                           CaixaView.caixa.setSaldoFinal(CaixaView.caixa.getSaldoFinal().subtract(new BigDecimal(saida)));
                        }else
                            if (jrbValeAlimentacao.isSelected()){
                               CaixaView.caixa.setValeAlimentacaoSaida(CaixaView.caixa.getValeAlimentacaoSaida().add(new BigDecimal(saida)));
                               CaixaView.caixa.setTotalSaida(CaixaView.caixa.getTotalSaida().add(new BigDecimal(saida)));
                               CaixaView.caixa.setSaldoValeAliment(CaixaView.caixa.getSaldoValeAliment().subtract(new BigDecimal(saida)));
                               CaixaView.caixa.setSaldoFinal(CaixaView.caixa.getSaldoFinal().subtract(new BigDecimal(saida)));
                            }
                               
                if (jrbSaidaTransferencia.isSelected()){
                   //Salvar Transferencia de Saldo, na respectiva Conta de transferência.
                   BancoMovimento bm = new BancoMovimento();
                   BancoMovimentoDAO daoBm = new BancoMovimentoDAO();
                   Banco bc = new Banco();
                   Date y = new Date();
                   BigDecimal saldo;
                   bc = listaBanco.get(jcbBanco.getSelectedIndex());
                
                   //Pegando o últiomo Registro da Conta Banco
                   if (!bc.getBancoMovimentoList().isEmpty()){
                      int ultimoRegistro = bc.getBancoMovimentoList().size() - 1;
                      saldo = bc.getBancoMovimentoList().get(ultimoRegistro).getSaldo();
                      saldo = saldo.add(new BigDecimal(saida));
                   }else
                       saldo = new BigDecimal(saida);
                             
                    bm.setIdBanco(listaBanco.get(jcbBanco.getSelectedIndex()));
                    bm.setDtLancamento(y);
                    bm.setVlEntrada(new BigDecimal(saida));               
                    bm.setObs("Transferencia de saldo do Caixa ID: ("+caixa.getId()+") em "+formaPagto);
                    bm.setSaldo(saldo);
                
                    daoBm.salvar(bm); 
                    JOptionPane.showMessageDialog(null, "Transferência de Saldo Realizado com Sucesso!!!");              
                }else
                    JOptionPane.showMessageDialog(null, "Saída de Saldo Realizado com Sucesso!!!");              
            }else
                if (jrbEntrada.isSelected()){
                   descricao = "ENTRADA - ACRÉSCIMO";
                   saida = "";
                   entrada = jtfValor.getText();
                   entrada = entrada.replace(".", "");
                   entrada = entrada.replace(",", "."); 
                   //Coloca Fonte a Direita na cor Azul
                   jTable1.getColumnModel().getColumn(2).setCellRenderer(new JTableFonteColunaDireitaAzul());    
          
                   if (jrbDinheiro.isSelected()){
                      CaixaView.caixa.setDinheiroEntrada(CaixaView.caixa.getDinheiroEntrada().add(new BigDecimal(entrada)));
                      CaixaView.caixa.setTotalEntrada(CaixaView.caixa.getTotalEntrada().add(new BigDecimal(entrada)));
                      CaixaView.caixa.setSaldoDinheiro(CaixaView.caixa.getSaldoDinheiro().add(new BigDecimal(entrada)));
                      CaixaView.caixa.setSaldoFinal(CaixaView.caixa.getSaldoFinal().add(new BigDecimal(entrada)));
                   }else 
                       if (jrbCheque.isSelected()){
                          CaixaView.caixa.setChequeEntrada(CaixaView.caixa.getChequeEntrada().add(new BigDecimal(entrada)));
                          CaixaView.caixa.setTotalEntrada(CaixaView.caixa.getTotalEntrada().add(new BigDecimal(entrada)));
                          CaixaView.caixa.setSaldoFinal(CaixaView.caixa.getSaldoFinal().add(new BigDecimal(entrada)));
                        }           
               }else{
                    JOptionPane.showMessageDialog(null, "Selecione, se é Entrada ou Saída");
                    jtfValor.requestFocus();
                    return;
                }
        
        
        if (jtfObs.getText().equals("") && jrbSaidaTransferencia.isSelected())
            obs = "TRANSFERENCIA";
        else
            if (jtfObs.getText().equals("") && jrbSaidaSangria.isSelected() || jrbSaidaPagto.isSelected())
               obs = "RETIRADA";
            else
                obs = jtfObs.getText();
        
        //Salvar Atualização do Caixa
        caixaDAO.alterarCaixa(CaixaView.caixa);
        

        //Setar os Campos no Formulário do Caixa, com informações atualizadas do banco de dados.
        //Entradas                  
        CaixaView.jtfDinheiroEntrada.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getDinheiroEntrada()));
        CaixaView.jtfChequeEntrada.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getChequeEntrada()));
        CaixaView.jtfCartaoCredito.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getCartaoCredito()));
        CaixaView.jtfCartaoDebito.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getCartaoDebito()));
        CaixaView.jtfValeAlimentacao.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getValeAlimentacao()));
             
        CaixaView.jtfTotalEntrada.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getTotalEntrada()));
       
        //Saidas
        CaixaView.jtfDinheiroSaida.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getDinheiroSaida()));
        CaixaView.jtfChequeSaida.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getChequeSaida()));
        CaixaView.jtfCartaoCreditoSaida.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getCartaoCreditoSaida()));
        CaixaView.jtfCartaoDebitoSaida.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getCartaoDebitoSaida()));
        CaixaView.jtfValeAlimentSaida.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getValeAlimentacaoSaida()));
             
        CaixaView.jtfTotalSaida.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getTotalSaida()));
        //Saldos
        CaixaView.jtfSaldoDinheiro.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getSaldoDinheiro()));
        CaixaView.jtfSaldoCartaoCredito.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getSaldoCartaoCredito()));
        CaixaView.jtfSaldoCartaoDebito.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getSaldoCartaoDebito()));
        CaixaView.jtfSaldoCheque.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getSaldoCheque()));
        CaixaView.jtfSaldoValeAliment.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getSaldoValeAliment()));
        
        CaixaView.jtfSaldoFinal.setText(new DecimalFormat("#,##0.00").format(CaixaView.caixa.getSaldoFinal()));
         
         //Saldos Cálculos Criando as variaveis, para apurar o resultado.
//         float totalEntrada = 0, totalSaida = 0, saldoFinal = 0, saldoDinheiro = 0;
                   
        //Carregar Objeto Itens do Caixa.
        itensCaixa.setIdCaixa(CaixaView.caixa);
        //Data e Hora
        try {
            itensCaixa.setDtHora(formatadorHD.parse(dataHora));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro de Data. "+ex.getMessage());
        }
        itensCaixa.setDescricao(descricao);
        
        //Valor de Entrada
        if (entrada.equals("0.00") || entrada.equals(""))
            itensCaixa.setVlEntrada(BigDecimal.ZERO);
        else{                  
           itensCaixa.setVlEntrada(new BigDecimal(entrada));
           entrada = jtfValor.getText();
        }
        //Valor de Saida       
        if (saida.equals("0.00") || saida.equals(""))
            itensCaixa.setVlSaida(BigDecimal.ZERO);
        else{
           // saida = saida.replace(".", "");
            saida = saida.replace(",", ".");
            itensCaixa.setVlSaida(new BigDecimal(saida));
            saida = jtfValor.getText();
        }
        itensCaixa.setFormaPagto(formaPagto);
        itensCaixa.setObs(obs);
//        itensCaixa.setPedido(null);
        itensCaixa.setTipo("LANCAMENTO");
        //Salva o Iten do Caixa e Retorna o Objeto com ID. Caso queira excluir o lancamento        
        itensCaixa = itensCaixaDAO.salvar(itensCaixa);     
        
        //Carregar JTable do CaixaView.                   
        amodel.addRow(new Object[]{dataHora, descricao, entrada, saida, formaPagto, obs, itensCaixa.getId()});        
        jButton2ActionPerformed(evt);       
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jtfObsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfObsFocusLost
        jtfObs.setText(jtfObs.getText().toUpperCase());
    }//GEN-LAST:event_jtfObsFocusLost

    private void jtfValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorKeyTyped
        String caracteres="0987654321,";
        if (!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_jtfValorKeyTyped

    private void jrbSaidaTransferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbSaidaTransferenciaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbSaidaTransferencia.isSelected()){
                carregaCombobox();
                jLabel3.setVisible(true);
                jcbBanco.setVisible(true);                
                jcbBanco.requestFocus();
            }else
                jrbSaidaSangria.requestFocus();
        }
    }//GEN-LAST:event_jrbSaidaTransferenciaKeyPressed

    private void jrbSaidaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSaidaTransferenciaActionPerformed

        if (jrbSaidaTransferencia.isSelected()){            
            carregaCombobox();
            jLabel3.setVisible(true);
            jcbBanco.setVisible(true);
            jcbBanco.requestFocus();            
        }else{
            jLabel3.setVisible(false);
            jcbBanco.setVisible(false);
            jrbSaidaSangria.requestFocus();
        }
            
             
            
    }//GEN-LAST:event_jrbSaidaTransferenciaActionPerformed

    private void jcbBancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbBancoKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER){
           
           jtfValor.requestFocus();
       }

    }//GEN-LAST:event_jcbBancoKeyPressed

    private void jrbSaidaSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSaidaSangriaActionPerformed

        jLabel3.setVisible(false);
        jcbBanco.setVisible(false);
        jtfValor.requestFocus();
    }//GEN-LAST:event_jrbSaidaSangriaActionPerformed

    private void jrbSaidaPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSaidaPagtoActionPerformed

       jLabel3.setVisible(false);
        jcbBanco.setVisible(false);
        jtfValor.requestFocus();
    }//GEN-LAST:event_jrbSaidaPagtoActionPerformed

    private void jrbDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDinheiroActionPerformed

        jtfValor.setText(CaixaView.jtfSaldoDinheiro.getText());
        System.out.println("saldo dinheiro ="+CaixaView.jtfSaldoDinheiro.getText());
    }//GEN-LAST:event_jrbDinheiroActionPerformed

    private void jrbCartaoDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCartaoDebitoActionPerformed

        jtfValor.setText(CaixaView.jtfSaldoCartaoDebito.getText()); 
        jrbSaidaTransferencia.requestFocus();
    }//GEN-LAST:event_jrbCartaoDebitoActionPerformed

    private void jrbCartaoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCartaoCreditoActionPerformed

         jtfValor.setText(CaixaView.jtfSaldoCartaoCredito.getText());
         jrbSaidaTransferencia.requestFocus();
    }//GEN-LAST:event_jrbCartaoCreditoActionPerformed

    private void jrbChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbChequeActionPerformed

       jtfValor.setText(CaixaView.jtfSaldoCheque.getText());
       jrbSaidaTransferencia.requestFocus();
    }//GEN-LAST:event_jrbChequeActionPerformed

    private void jrbValeAlimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbValeAlimentacaoActionPerformed

        jtfValor.setText(CaixaView.jtfSaldoValeAliment.getText());
        jrbSaidaTransferencia.requestFocus();
    }//GEN-LAST:event_jrbValeAlimentacaoActionPerformed

    private void jrbCartaoDebitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbCartaoDebitoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbCartaoDebito.isSelected()){
                jtfValor.setText(CaixaView.jtfSaldoCartaoDebito.getText());
                jrbSaidaTransferencia.requestFocus();
            }else
                jrbCartaoCredito.requestFocus();
        }
    }//GEN-LAST:event_jrbCartaoDebitoKeyPressed

    private void jrbCartaoCreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbCartaoCreditoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbCartaoCredito.isSelected()){
                jtfValor.setText(CaixaView.jtfSaldoCartaoCredito.getText());
                jrbSaidaTransferencia.requestFocus();
            }else
                jrbCheque.requestFocus();
        }
    }//GEN-LAST:event_jrbCartaoCreditoKeyPressed

    private void jrbValeAlimentacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbValeAlimentacaoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jrbValeAlimentacao.isSelected()){
                jtfValor.setText(CaixaView.jtfSaldoValeAliment.getText());
                jrbSaidaTransferencia.requestFocus();
            }else
                jrbDinheiro.requestFocus();
        }
    }//GEN-LAST:event_jrbValeAlimentacaoKeyPressed

    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op)){
                jbtSalvarActionPerformed(null);
            }
        }

    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jButton2ActionPerformed(null);
        }  
    }//GEN-LAST:event_jButton2KeyPressed

     private void carregaCombobox(){
        
        daoBanco = new BancoDAO();
       
        listaBanco = daoBanco.listBanco();       
       
        jcbBanco.removeAllItems();
        for (Banco banco : listaBanco){
            jcbBanco.addItem(banco.getDescricao());
        }
        
       
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CaixaLancamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CaixaLancamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CaixaLancamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CaixaLancamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CaixaLancamentoView dialog = new CaixaLancamentoView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox<String> jcbBanco;
    private javax.swing.JRadioButton jrbCartaoCredito;
    private javax.swing.JRadioButton jrbCartaoDebito;
    private javax.swing.JRadioButton jrbCheque;
    private javax.swing.JRadioButton jrbDinheiro;
    private javax.swing.JRadioButton jrbEntrada;
    private javax.swing.JRadioButton jrbSaidaPagto;
    private javax.swing.JRadioButton jrbSaidaSangria;
    private javax.swing.JRadioButton jrbSaidaTransferencia;
    private javax.swing.JRadioButton jrbValeAlimentacao;
    private javax.swing.JTextField jtfObs;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
