/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.CaixaDAO;
import dao.PessoaDAO;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Caixa;
import model.CaixaItens;
import model.Pessoa;
import net.sf.jasperreports.engine.JRException;
import relatoriosView.ImprimeRelatorio;
import relatoriosView.caixa.RelCaixa;

/**
 *
 * @author daniel
 */
public class HistoricoCaixaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistoricoCaixaView
     */
    
    List<Caixa> listaCaixa;
    DateFormat df = new SimpleDateFormat ("dd/MM/yyyy");
    SimpleDateFormat sdfDH = new SimpleDateFormat("dd/MM/yyyy'-'HH':'mm");
    List<Pessoa> listaUsuario;
    
    public HistoricoCaixaView() {
        initComponents();
        CarregaComboBox();
        
//        for (Pessoa p : listaUsuario){
//            if (p.getId() == menuView.Menu.colaborador.getId())
//                jcbUsuario.setSelectedItem(p.getNome());
//        }
        jcbUsuario.setSelectedItem(menuView.Menu.colaborador.getNome());
      //  jrbExibirMaisRecent.setSelected(true);
        jbPesquisaActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbExibirMaisRecent = new javax.swing.JRadioButton();
        jcbExibirUltimos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jrbPesquisaPeriodo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jftDataIni = new javax.swing.JFormattedTextField();
        jftDataFim = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbUsuario = new javax.swing.JComboBox<>();
        jbPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtImprimir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jrbExibirMaisRecent);
        jrbExibirMaisRecent.setSelected(true);
        jrbExibirMaisRecent.setText("Exibir os mais Recentes");

        jcbExibirUltimos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50" }));

        jLabel1.setText("Últimos Registros");

        buttonGroup1.add(jrbPesquisaPeriodo);
        jrbPesquisaPeriodo.setText("Filtrar por Período");

        jLabel2.setText("à");

        try {
            jftDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Colaborador");

        jcbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));

        jbPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Find.png"))); // NOI18N
        jbPesquisa.setToolTipText("Atualizar");
        jbPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbExibirMaisRecent)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbExibirUltimos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbPesquisaPeriodo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jftDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbExibirMaisRecent)
                    .addComponent(jrbPesquisaPeriodo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbExibirUltimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jftDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jftDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ABERTO EM", "FECHADO EM", "TOTAL ENTRADA", "TOTAL SAÍDA", "SALDO INICIAL", "SALDO FINAL", "COLABORADOR", "STATUS", "OBS", "ID CAIXA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(0);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print-icon.png"))); // NOI18N
        jbtImprimir.setText("Imprimir");
        jbtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimirActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.setToolTipText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        menuView.Menu.jbHistoricoCaixa.setEnabled(true);
        dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaActionPerformed
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
        amodel.setNumRows(0);
        CaixaDAO caixaDao = new CaixaDAO();        
        Date dataIni, dataFim;
        try{

            if (jrbPesquisaPeriodo.isSelected()){
               if (!jftDataIni.getText().equals("")){
                  dataIni = df.parse(jftDataIni.getText());
               }else{
                  JOptionPane.showMessageDialog(null, "A data inicial está vazia");
                  return;
               }
               if (!jftDataFim.getText().equals("")){
                  dataFim = df.parse(jftDataFim.getText());
               }else{
                  JOptionPane.showMessageDialog(null, "A data final está vazia");
                  return;
               }
            }else{
                  if (jrbExibirMaisRecent.isSelected()){
                     if (jcbUsuario.getSelectedItem().equals("TODOS"))
                        listaCaixa = caixaDao.listaCaixaTodosUsuario();
                     else
                        listaCaixa = caixaDao.listaCaixaPorUsuario(listaUsuario.get(jcbUsuario.getSelectedIndex()));
                  }
            }            
            if (listaCaixa.isEmpty()){
                JOptionPane.showMessageDialog(null, "Este Usuário, não têm Registros no CAIXA");
                return;
            }        
            
            //Popular jTable
            String dtAbertura = null;
            String dtFechado = null;
            BigDecimal saldoInicial = new BigDecimal(BigInteger.ZERO);
            CaixaItens itensCaixa = new CaixaItens();
            for (Caixa caixa : listaCaixa){            
                
                //Formatar e converter data.
                dtAbertura = sdfDH.format(caixa.getDtAbertura());
                //Verifica se a data é vazia.
                if (caixa.getDtFechamento() == null)
                    dtFechado = "";
                else
                   dtFechado = sdfDH.format(caixa.getDtFechamento());
                //Pegar Saldo Inicial na Tabela Detalhe do Caixa.
                itensCaixa = caixa.getCaixaItensList().get(0);
                saldoInicial = (itensCaixa.getVlEntrada());

//              pagtoRel.setVencimento(df.format(pagto.getVencimento()));
//              pagtoRel.setParcelas(String.valueOf(pagto.getPagamentoCab().getQtd_parcela()));
//              pagtoRel.setTotal(new DecimalFormat("#,##0.00").format(pagto.getPagamentoCab().getVl_total()));
//              pagtoRel.setNumParcela(String.valueOf(pagto.getNum_parcela()));
//                       
//              pagtoRel.setVlParcela(new DecimalFormat("#,##0.00").format(pagto.getVl_parcela()));
//                
                amodel.addRow(new Object[]{dtAbertura, dtFechado, caixa.getTotalEntrada(), caixa.getTotalSaida(),
                saldoInicial, caixa.getSaldoFinal(), caixa.getIdUsuario().getNome(), caixa.getStatus(), caixa.getObs(), caixa.getId()});
           
            }
//             DefaultTableCellRenderer coluna = new DefaultTableCellRenderer();
//             jTable1.getColumnModel().getColumn(2).setCellRenderer(coluna);
              
            
            
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Problemas ao Carregar Histórico do Caixa"+ex.getMessage());
            ex.printStackTrace();
        }       
    }//GEN-LAST:event_jbPesquisaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

         if (evt.getClickCount() == 2) {
           //JOptionPane.showMessageDialog(null, "chamar form caixa");
           Long idCaixa = Long.parseLong(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
           
           CaixaVisaoView caixaVisao = new CaixaVisaoView(new java.awt.Frame(), true, idCaixa);
           caixaVisao.setTitle("Caixa Visão: " + jTable1.getValueAt(jTable1.getSelectedRow(), 6));
           caixaVisao.setLocationRelativeTo(null); // centraliza a tela
           caixaVisao.setVisible(true);
           
           
           
        } 
         
//         else if (evt.getClickCount() == 1) {
//            btnOk.setEnabled(true);
//        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jButton1ActionPerformed(null);
        }          
    }//GEN-LAST:event_jButton1KeyPressed

    private void jbtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimirActionPerformed
     //   CaixaDAO caixaDAO = new CaixaDAO();
        ImprimeRelatorio imprimir = new ImprimeRelatorio();
        List<RelCaixa> listaHistCaixa = new ArrayList<>();
        RelCaixa relHistCaixa = new RelCaixa();
        float totalEntrada = 0, totalSaida = 0, totalSaldoFinal = 0;
        for (int i = 0; i < jTable1.getRowCount(); i ++){
            
            relHistCaixa.setAberto(jTable1.getValueAt(i, 0).toString());
            relHistCaixa.setFechado(jTable1.getValueAt(i, 1).toString());
            relHistCaixa.setTotalEntrada(jTable1.getValueAt(i, 2).toString());
            relHistCaixa.setTotalSaida(jTable1.getValueAt(i, 3).toString());
            relHistCaixa.setSaldoFinal(jTable1.getValueAt(i, 5).toString());
            relHistCaixa.setColaborador(jTable1.getValueAt(i, 6).toString());
            
            totalEntrada = totalEntrada + Float.parseFloat(jTable1.getValueAt(i, 2).toString());
            totalSaida = totalSaida + Float.parseFloat(jTable1.getValueAt(i, 3).toString());           
            totalSaldoFinal = totalSaldoFinal + Float.parseFloat(jTable1.getValueAt(i, 5).toString());
           
            
            listaHistCaixa.add(new RelCaixa(relHistCaixa.getAberto(), relHistCaixa.getFechado(),
            relHistCaixa.getTotalEntrada(), relHistCaixa.getTotalSaida(), relHistCaixa.getSaldoFinal(),
            relHistCaixa.getColaborador()));
        }
           
        String totalEntStr = String.valueOf(new DecimalFormat("#,##0.00").format(totalEntrada));
        String totalSaiStr = String.valueOf(new DecimalFormat("#,##0.00").format(totalSaida));
        String totalSaldoStr = String.valueOf(new DecimalFormat("#,##0.00").format(totalSaldoFinal));
        
        try {
            imprimir.historicoCaixa(listaHistCaixa, totalEntStr, totalSaiStr, totalSaldoStr);
        } catch (JRException ex) {
            Logger.getLogger(HistoricoCaixaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jbtImprimirActionPerformed

    private void CarregaComboBox(){
        PessoaDAO pessoaDao = new PessoaDAO();
        
        listaUsuario = pessoaDao.listaColaboradorALL();
        
        jcbUsuario.removeAllItems();
        
        for (Pessoa usuario : listaUsuario){
            jcbUsuario.addItem(usuario.getNome());
        }          
        jcbUsuario.addItem("TODOS");
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HistoricoCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HistoricoCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HistoricoCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HistoricoCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HistoricoCaixaView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbPesquisa;
    private javax.swing.JButton jbtImprimir;
    private javax.swing.JComboBox<String> jcbExibirUltimos;
    private javax.swing.JComboBox<String> jcbUsuario;
    private javax.swing.JFormattedTextField jftDataFim;
    private javax.swing.JFormattedTextField jftDataIni;
    private javax.swing.JRadioButton jrbExibirMaisRecent;
    private javax.swing.JRadioButton jrbPesquisaPeriodo;
    // End of variables declaration//GEN-END:variables
}
