/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.ProdutoDAO;
import java.text.DecimalFormat;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author daniel
 */
public class OrcamentoDetView extends javax.swing.JDialog {

    /**
     * Creates new form OrcamentoDetView
     */
    private ProdutoDAO prodDao;
    private Produto produto;
    float vltotal, vlUnit, qtd, estoque;
    
    public OrcamentoDetView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        rowSorterToStringConverter1 = new converter.RowSorterToStringConverter();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jtfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jtfCodProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfSubTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfValorUnitario = new javax.swing.JTextField();
        jtfUnidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfDesconto = new javax.swing.JTextField();
        jrbVarejo = new javax.swing.JRadioButton();
        jrbAtacado = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jbtSalvar = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();

        rowSorterToStringConverter1.setTable(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Produtos"));

        jtfPesquisa.setNextFocusableComponent(jbtSair);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), jtfPesquisa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        jtfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓD. PRODUTO", "DESCRIÇÃO", "ESTOQUE", "R$ VAREJO", "R$ ATACADO", "MARCA", "UNIDADE", "CÓD. BARRAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 315, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Orçamento"));

        jtfCodProd.setEnabled(false);
        jtfCodProd.setNextFocusableComponent(jtfQuantidade);
        jtfCodProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodProdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodProdKeyTyped(evt);
            }
        });

        jLabel1.setText("CÓD. PRODUTO");

        jtfDescricao.setEnabled(false);

        jLabel2.setText("DESCRIÇÃO");

        jLabel4.setText("QUANTIDADE");

        jtfQuantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfQuantidade.setEnabled(false);
        jtfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfQuantidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfQuantidadeKeyTyped(evt);
            }
        });

        jLabel6.setText("R$ SUBTOTAL");

        jtfSubTotal.setEditable(false);
        jtfSubTotal.setBackground(new java.awt.Color(237, 238, 138));
        jtfSubTotal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jtfSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfSubTotal.setEnabled(false);
        jtfSubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSubTotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSubTotalKeyTyped(evt);
            }
        });

        jLabel7.setText("R$ UNITÁRIO");

        jtfValorUnitario.setEditable(false);
        jtfValorUnitario.setBackground(new java.awt.Color(220, 220, 110));
        jtfValorUnitario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jtfValorUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfValorUnitario.setEnabled(false);

        jtfUnidade.setEditable(false);
        jtfUnidade.setEnabled(false);

        jLabel3.setText("Unidade");

        jtfTotal.setEnabled(false);
        jtfTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTotalKeyPressed(evt);
            }
        });

        jLabel8.setText("R$ TOTAL");

        jLabel9.setText("DESC.%");

        jtfDesconto.setEnabled(false);
        jtfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescontoKeyPressed(evt);
            }
        });

        buttonGroup1.add(jrbVarejo);
        jrbVarejo.setText("VAREJO");
        jrbVarejo.setEnabled(false);
        jrbVarejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVarejoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbAtacado);
        jrbAtacado.setText("ATACADO");
        jrbAtacado.setEnabled(false);
        jrbAtacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAtacadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jtfQuantidade)
                    .addComponent(jtfCodProd))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(jtfDesconto)))
                            .addComponent(jtfDescricao))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbVarejo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbAtacado)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbVarejo)
                    .addComponent(jrbAtacado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setEnabled(false);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.setToolTipText("Fechar Formulário");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jbtSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSairKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtSalvar)
                .addComponent(jbtSair))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            jtfCodProd.setEnabled(true);
            jtfDescricao.setEnabled(true);
            jtfCodProd.requestFocus();
        }
    }//GEN-LAST:event_jtfPesquisaKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

          jtfCodProd.setEnabled(true);
          jtfDescricao.setEnabled(true);
          jtfQuantidade.setEnabled(true);
          jtfValorUnitario.setEnabled(true);
          jtfUnidade.setEnabled(true);
          jtfCodProd.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
          jtfDescricao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
          jtfValorUnitario.setText(new DecimalFormat("#,##0.00").format(Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString())));//
          jtfUnidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
          estoque = (Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString()));
          jrbVarejo.setEnabled(true);
          jrbAtacado.setEnabled(true);
          jrbVarejo.setSelected(true);
          jtfQuantidade.requestFocus();
          
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

       

    }//GEN-LAST:event_jTable1KeyPressed

    private void jtfCodProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodProdKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            prodDao = new ProdutoDAO();
            produto = new Produto();

            if (jtfCodProd.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Código do Produto não pode ficar em branco ou vazio !!!");
                jtfCodProd.requestFocus();
            } else {
                Long id_produto = (Long.parseLong(jtfCodProd.getText()));
                produto = prodDao.produtoId(id_produto);
                estoque = produto.getEstoque();
                if (produto == null) {
                    JOptionPane.showMessageDialog(null, "Este Produto não existe");
                    jtfCodProd.requestFocus();
                } else if (estoque <= 0) {
                    JOptionPane.showMessageDialog(null, "Este Produto não têm no Estoque!!!");
                    jtfCodProd.requestFocus();
                } else {                    
                    jtfValorUnitario.setEnabled(true);
                    jtfDescricao.setEnabled(true);
                    jtfDescricao.setText(produto.getDescricao());
                    jtfValorUnitario.setText(String.valueOf(produto.getVlVenda()));
                    jtfValorUnitario.setText(new DecimalFormat("#,##0.00").format(Float.parseFloat(jtfValorUnitario.getText())));
                    jtfUnidade.setText(produto.getUnidade().getSigla());
                    jtfQuantidade.setEnabled(true);
                    jtfQuantidade.requestFocus();
                }

            }

        }
    }//GEN-LAST:event_jtfCodProdKeyPressed

    private void jtfQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQuantidadeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (jtfQuantidade.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "A Quantidade não pode ficar em branco ou vazio !!!");
                jtfQuantidade.requestFocus();
            } 
//            else if (estoque <= 0) {
//                JOptionPane.showMessageDialog(null, "Este Produto não têm no Estoque.");
//                jtfCodProd.requestFocus();
//                return;}
            else {
                String vlUnitStr = jtfValorUnitario.getText();
                vlUnitStr = vlUnitStr.replace(".", "");
                vlUnitStr = vlUnitStr.replace(",", ".");
                vlUnit = (Float.parseFloat(vlUnitStr));
                qtd = (Float.parseFloat(jtfQuantidade.getText()));
                vltotal = (qtd * vlUnit);
                jtfValorUnitario.setEnabled(true);
                jtfSubTotal.setEnabled(true);
                jtfSubTotal.setText(String.valueOf(new DecimalFormat("#,##0.00").format((vltotal))));
                jtfDesconto.setEnabled(true);
                jtfDesconto.requestFocus();
            }

        }
    }//GEN-LAST:event_jtfQuantidadeKeyPressed

    private void jtfQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQuantidadeKeyTyped
        String caracteres="0987654321.";
        if (!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfQuantidadeKeyTyped

    private void jtfSubTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSubTotalKeyPressed
       
    }//GEN-LAST:event_jtfSubTotalKeyPressed

    private void jtfSubTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSubTotalKeyTyped
        
    }//GEN-LAST:event_jtfSubTotalKeyTyped

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        DefaultTableModel amodel = (DefaultTableModel) OrcamentoCabView.jTable2.getModel();
        String total; 
       
        if (jtfQuantidade.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite a Quantidade.");
            jtfQuantidade.requestFocus();
            return;
        }else
            if (jtfCodProd.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Digite o Código do Produto.");
               jtfCodProd.requestFocus();
               return;
            }     
        int idProduto = Integer.parseInt(jtfCodProd.getText());
        for (int i = 0; i < amodel.getRowCount(); i++){
            int idProdutoOrcamento = Integer.parseInt(amodel.getValueAt(i, 1).toString());
            if (idProdutoOrcamento == idProduto){
               JOptionPane.showMessageDialog(null, "Produto já Inserido neste Orçamento");
               idProduto = 0;
               break;              
            }            
        }
        
        //SE o idProduto for diferente de 0 é porque o produto não existe no orcamento.
        if (idProduto != 0){
            String tipoVenda = null;
           if (jrbVarejo.isSelected()) 
               tipoVenda = "V";
           else
               if (jrbAtacado.isSelected())
                   tipoVenda = "A";
                       
           OrcamentoCabView.subtotal = (OrcamentoCabView.subtotal + vltotal);
           OrcamentoCabView.contItem = OrcamentoCabView.contItem + 1;
           OrcamentoCabView.jtfSubTotal.setText(new DecimalFormat("#,##0.00").format(OrcamentoCabView.subtotal));
          
           amodel.addRow(new Object[]{String.valueOf(OrcamentoCabView.contItem), jtfCodProd.getText(), jtfDescricao.getText(), jtfQuantidade.getText(),jtfUnidade.getText(),
           jtfValorUnitario.getText(),jtfDesconto.getText(), jtfTotal.getText(), tipoVenda});
        }
          limpar();
          habilitar(false);
          jtfPesquisa.setEnabled(true);
          jbtSalvar.setEnabled(false);
          jtfPesquisa.requestFocus();
       
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtSalvarActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        // TODO add your handling code here:
        // dispose();
        OrcamentoCabView.jtfDesconto.requestFocus();
        dispose();
        //Habilita o menu de cep.
        //  MenuPrincipal.categoriaMenuItem.setEnabled(true);
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jtfCodProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodProdKeyTyped
        String caracteres="0987654321.";
        if (!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfCodProdKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void jbtSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSairKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtSairActionPerformed(null);
        }  
   
    }//GEN-LAST:event_jbtSairKeyPressed

    private void jtfDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoKeyPressed
         float desconto = 0, vlpago =0;
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfDesconto.getText().equals("")){
                jtfDesconto.setText("0.0");
                jtfTotal.setEnabled(true);
                jtfTotal.requestFocus();
            }else{
                desconto = Float.parseFloat(jtfDesconto.getText());
                vlpago = (vltotal -(vltotal*desconto/100));
                jtfTotal.setEnabled(true);
                jtfTotal.setText(new DecimalFormat("#,##0.00").format(vlpago));
                vltotal = vlpago;
                jbtSalvar.setEnabled(true);
                jbtSalvar.requestFocus();
            }
                
            
        }
    }//GEN-LAST:event_jtfDescontoKeyPressed

    private void jtfTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTotalKeyPressed
         float desconto = 0, vlpago = 0;
        if (evt.getKeyCode() == evt.VK_ENTER){
            vlpago = vltotal;
            if (jtfTotal.getText().equals("")){                
                jtfTotal.setText(new DecimalFormat("#,##0.00").format(vlpago));
                
            }else {
               desconto = 0;                          
               vlpago = Float.parseFloat(jtfTotal.getText());
               desconto = ((vlpago / vltotal)*100);
               desconto = (100 - desconto);
               jtfDesconto.setText(new DecimalFormat("#,##0.00").format(desconto));
               jtfTotal.setText(new DecimalFormat("#,##0.00").format(vlpago));  
               vltotal= vlpago; 
            }
            jbtSalvar.setEnabled(true);
            jbtSalvar.requestFocus(); 
        }  
    }//GEN-LAST:event_jtfTotalKeyPressed

    private void jrbVarejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVarejoActionPerformed
        
        if (jrbVarejo.isSelected()){
            
            
            jtfValorUnitario.setText("");
            jtfValorUnitario.setText(new DecimalFormat("#,##0.00").format(Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString())));//
            jtfSubTotal.setText("");
            jtfTotal.setText("");
            
            jtfQuantidade.setText("");
            jtfQuantidade.requestFocus();
        }
        
        
        
    }//GEN-LAST:event_jrbVarejoActionPerformed

    private void jrbAtacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAtacadoActionPerformed

         if (jrbAtacado.isSelected()){
            
            
            jtfValorUnitario.setText("");
            jtfValorUnitario.setText(new DecimalFormat("#,##0.00").format(Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString())));//
            jtfSubTotal.setText("");
            jtfTotal.setText("");
            
            jtfQuantidade.setText("");
            jtfQuantidade.requestFocus();
        }
    }//GEN-LAST:event_jrbAtacadoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrcamentoDetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrcamentoDetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrcamentoDetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrcamentoDetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                OrcamentoDetView dialog = new OrcamentoDetView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JRadioButton jrbAtacado;
    private javax.swing.JRadioButton jrbVarejo;
    public static javax.swing.JTextField jtfCodProd;
    private javax.swing.JTextField jtfDesconto;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfQuantidade;
    private javax.swing.JTextField jtfSubTotal;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfUnidade;
    private javax.swing.JTextField jtfValorUnitario;
    private converter.RowSorterToStringConverter rowSorterToStringConverter1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void carregaTable(){
        List<Produto> listaProduto; 
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
        amodel.setNumRows(0);
        ProdutoDAO proDAO = new ProdutoDAO();                   
        listaProduto = null;        
        listaProduto = proDAO.listaProduto();        
        String valorUnit = null;
        for (Produto produto : listaProduto){       
           // produto.setVlVenda(new DecimalFormat("#,##0.00").format(Float.parseFloat(produto.getVlVenda())));
          //  valorUnit = ();valorUnit = String.valueOf
            amodel.addRow(new Object[]{produto.getId(),produto.getDescricao(), produto.getEstoque(), produto.getVlVenda(), produto.getVlVendaAtacado(), produto.getMarca().getDescricao(), produto.getUnidade().getSigla(), produto.getCodBarras()});            
        }
        
    }
  
    public void limpar(){
        jtfCodProd.setText("");
        jtfDescricao.setText("");
        jtfQuantidade.setText("");
        jtfPesquisa.setText("");
        jtfValorUnitario.setText("");
        jtfSubTotal.setText("");
        jtfUnidade.setText("");
        jtfDesconto.setText("");
        jtfTotal.setText("");
        jrbAtacado.setSelected(false);
        jrbVarejo.setSelected(false);
    }
    public void habilitar(boolean habilita){
        jtfCodProd.setEnabled(habilita);
        jtfDescricao.setEnabled(habilita);
        jtfQuantidade.setEnabled(habilita);
        jtfPesquisa.setEnabled(habilita);
        jtfValorUnitario.setEnabled(habilita);
        jtfSubTotal.setEnabled(habilita);
        jtfUnidade.setEnabled(habilita);
        jtfDesconto.setEnabled(habilita);
        jtfTotal.setEnabled(habilita);
        jrbAtacado.setEnabled(habilita);
        jrbVarejo.setEnabled(habilita);
    }

}
