/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.BancoDAO;
import dao.BancoMovimentoDAO;

import dao.CategoriaContaDAO;
import dao.FornecedorDAO;
import dao.PagamentoCabDAO;
import dao.TipoPagamentoDAO;
import java.awt.Color;
import java.awt.Component;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Banco;
import model.BancoMovimento;

import model.CategoriaConta;
import model.PagamentoCab;
import model.PagamentoDet;
import model.Pessoa;
import model.TipoPagamento;

/**
 *
 * @author del
 */
public class PagamentoCabView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PagamentoCabView
     */
    FornecedorDAO fornecedorDAO;
    TipoPagamentoDAO tipoPagtoDAO;
    CategoriaContaDAO categoriaContaDAO;
    BancoDAO bancoDAO;
    List<Banco> listBanco;
    List<TipoPagamento> listTipoPagto;
    List<Pessoa> listFornecedor;
    List<CategoriaConta> listCategoriaConta;
    List<PagamentoCab> listaPgtCab;
    String operacao;
    PagamentoCab pgtCab = new PagamentoCab();
    PagamentoDet pgtDet = new PagamentoDet();
    PagamentoCabDAO pgtCabDAO = new PagamentoCabDAO();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    PagamentoCabDAO pagtoDAO = new PagamentoCabDAO();
    public PagamentoCabView() {
        initComponents();
        habilita(false);
        carregaTable();
        jTabbedPane1.setEnabled(true);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setSelectedIndex(0);
        jtfPesquisa.setEnabled(true);
    //    carregaCombobox();
        jbtCancela.setEnabled(false);
        jtfPesquisa.requestFocus();
        
        //Pegando o mes corrente para somar as contas do mes.
        GregorianCalendar calendar = new GregorianCalendar();
        // int dia = calendar.get(GregorianCalendar.DAY_OF_MONTH);
        int mes = calendar.get(GregorianCalendar.MONTH);
        //String mes = String.copyValueOf(mesInt);
     //   System.out.println("Total a pagar no mes"+pgtCabDAO.somaTotalAPagarMesCorrente());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        rowSorterToStringConverter1 = new converter.RowSorterToStringConverter();
        jPanel1 = new javax.swing.JPanel();
        jtfPesquisa = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jtfDtEmissao = new javax.swing.JTextField();
        jtfDtVencimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNumDoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbFornecedor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jtfQtdeParcelas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfSubTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfJurosCab = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfDescontoCab = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfVlTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtfNumParcela = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcbTipoPagto = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jcbBanco = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jtfDtPagto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtfJurosDet = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtfDescontoDet = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtfMulta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jtfVlParcela = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtfVlPago = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jlbSaldoDev = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtNovo = new javax.swing.JButton();
        jbtCancela = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();
        jbtAlterar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();

        rowSorterToStringConverter1.setTable(jTable1);

        setMaximizable(true);
        setTitle("Contas à Pagar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Contas à Pagar"));

        jtfPesquisa.setNextFocusableComponent(jbtNovo);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), jtfPesquisa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes Conta à Pagar"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PARCELA", "TIPO PAGAMENTO", "BANCO", "VENCIMENTO", "R$ PARCELA", "R$ PAGO", "DATA PAGTO.", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setPreferredWidth(0);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabeçalho de Contas à Pagar"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NUM. DOC.", "DESCRIÇÃO", "FORNECEDOR", "QTD. PARC.", "VENCIMENTO", "R$ TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contas à Pagar", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabeçalho da Conta"));

        jtfCodigo.setEnabled(false);

        jLabel1.setText("CÓDIGO");

        jLabel2.setText("CATEGORIA");

        jtfDescricao.setEnabled(false);
        jtfDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescricaoFocusLost(evt);
            }
        });
        jtfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescricaoKeyPressed(evt);
            }
        });

        jtfDtEmissao.setEnabled(false);
        jtfDtEmissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDtEmissaoKeyPressed(evt);
            }
        });

        jtfDtVencimento.setBackground(new java.awt.Color(153, 238, 242));
        jtfDtVencimento.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jtfDtVencimento.setToolTipText("1º VENCIMENTO");
        jtfDtVencimento.setEnabled(false);
        jtfDtVencimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDtVencimentoKeyPressed(evt);
            }
        });

        jLabel3.setText("EMISSÃO");

        jLabel4.setText("VENCIMENTO");

        jLabel5.setText("Nº DOC.");

        jtfNumDoc.setEnabled(false);
        jtfNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumDocActionPerformed(evt);
            }
        });
        jtfNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNumDocKeyPressed(evt);
            }
        });

        jLabel6.setText("FORNECEDOR");

        jcbFornecedor.setEnabled(false);
        jcbFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbFornecedorKeyPressed(evt);
            }
        });

        jLabel7.setText("QTD. PARCELAS");

        jtfQtdeParcelas.setEnabled(false);
        jtfQtdeParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfQtdeParcelasKeyPressed(evt);
            }
        });

        jLabel8.setText("R$ SUB TOTAL");

        jtfSubTotal.setBackground(new java.awt.Color(254, 238, 166));
        jtfSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfSubTotal.setEnabled(false);
        jtfSubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSubTotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSubTotalKeyTyped(evt);
            }
        });

        jLabel9.setText("JUROS");

        jtfJurosCab.setEnabled(false);
        jtfJurosCab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfJurosCabKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfJurosCabKeyTyped(evt);
            }
        });

        jLabel10.setText("DESC.");

        jtfDescontoCab.setEnabled(false);
        jtfDescontoCab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescontoCabKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDescontoCabKeyTyped(evt);
            }
        });

        jLabel11.setText("%");

        jLabel12.setText("%");

        jLabel13.setText("R$ TOTAL");

        jtfVlTotal.setBackground(new java.awt.Color(254, 238, 124));
        jtfVlTotal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jtfVlTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlTotal.setEnabled(false);
        jtfVlTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfVlTotalKeyPressed(evt);
            }
        });

        jLabel14.setText("STATUS");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ABERTO", "FECHADO", "CANCELADO" }));
        jcbStatus.setEnabled(false);

        jLabel27.setText("DESCRIÇÃO");

        jcbCategoria.setEnabled(false);
        jcbCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbCategoriaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfQtdeParcelas))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(41, 41, 41))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jtfJurosCab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jtfDescontoCab, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfDtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(40, 40, 40))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfJurosCab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jtfQtdeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDescontoCab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jtfVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes da Conta"));

        jLabel15.setText("Nº PARCELA");

        jtfNumParcela.setEnabled(false);

        jLabel16.setText("TIPO PAGTO");

        jcbTipoPagto.setEnabled(false);
        jcbTipoPagto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbTipoPagtoKeyPressed(evt);
            }
        });

        jLabel17.setText("BANCO");

        jcbBanco.setEnabled(false);
        jcbBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbBancoKeyPressed(evt);
            }
        });

        jLabel18.setText("DATA PAGTO");

        jtfDtPagto.setEnabled(false);

        jLabel19.setText("JUROS");

        jtfJurosDet.setToolTipText("");
        jtfJurosDet.setEnabled(false);
        jtfJurosDet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfJurosDetKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfJurosDetKeyTyped(evt);
            }
        });

        jLabel20.setText("DESC.");

        jtfDescontoDet.setEnabled(false);
        jtfDescontoDet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescontoDetKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDescontoDetKeyTyped(evt);
            }
        });

        jLabel21.setText("%");

        jLabel22.setText("%");

        jLabel23.setText("MULTA/ACRÉSCIMO");

        jtfMulta.setEnabled(false);
        jtfMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMultaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfMultaKeyPressed(evt);
            }
        });

        jLabel24.setText("VALOR PARCELA");

        jtfVlParcela.setBackground(new java.awt.Color(254, 238, 124));
        jtfVlParcela.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jtfVlParcela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlParcela.setEnabled(false);

        jLabel25.setText("VALOR PAGO");

        jtfVlPago.setEditable(false);
        jtfVlPago.setBackground(new java.awt.Color(254, 238, 124));
        jtfVlPago.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jtfVlPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlPago.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfNumParcela))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jcbTipoPagto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfJurosDet, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel20))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(17, 17, 17)
                                .addComponent(jtfDescontoDet, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel24)
                    .addComponent(jtfVlParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jtfVlPago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDtPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(37, 37, 37))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDtPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfJurosDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescontoDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jtfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(229, 50, 50));
        jLabel26.setText("Saldo Devedor :");

        jlbSaldoDev.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jlbSaldoDev.setText("saldo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbSaldoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jlbSaldoDev))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados da Conta", jPanel5);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbtNovo.setText("Nova Conta");
        jbtNovo.setToolTipText("Adicionar nova Co nta à Pagar");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });
        jbtNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtNovoKeyPressed(evt);
            }
        });

        jbtCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jbtCancela.setText("Cancelar");
        jbtCancela.setToolTipText("Cancelar Conta à Pagar");
        jbtCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelaActionPerformed(evt);
            }
        });
        jbtCancela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtCancelaKeyPressed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setToolTipText("Salvar Conta à Pagar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.setToolTipText("Sair Conta à Pagar");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jbtSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSairKeyPressed(evt);
            }
        });

        jbtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit.png"))); // NOI18N
        jbtAlterar.setText("Fazer Pagamento");
        jbtAlterar.setToolTipText("Alterar Conta à Pagar");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });
        jbtAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtAlterarKeyPressed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });
        jbtExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtExcluirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jbtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtSalvar)
                        .addComponent(jbtExcluir)
                        .addComponent(jbtCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumDocActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        operacao = "salvar";
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
        //jtfDescricao.setEnabled(true);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); //você pode usar outras máscaras 
        Date y = new Date();
        jtfDtEmissao.setText(sdf.format(y));
        carregaCombobox();
        jcbFornecedor.setSelectedIndex(-1);
        jcbTipoPagto.setSelectedIndex(-1);
        jcbBanco.setSelectedIndex(-1);
        jtfPesquisa.setText("");
        jtfPesquisa.setEnabled(false);
        jbtNovo.setEnabled(false);
      //  jbtSalvar.setEnabled(true);
        jbtExcluir.setEnabled(false);
        jbtCancela.setEnabled(true);
        jbtAlterar.setEnabled(false);
        jcbStatus.setSelectedIndex(0);
        jlbSaldoDev.setVisible(false);
        jbtCancela.setEnabled(true);
        jcbCategoria.setEnabled(true);
        jcbCategoria.setSelectedIndex(-1);
        jcbTipoPagto.setEnabled(true);
        jcbCategoria.requestFocus();
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jtfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescricaoKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER){
           if (jtfDescricao.getText().equals("")){
               JOptionPane.showMessageDialog(null, "O campo descrição não pode ficar em branco");
               return;
           }else{
               jtfDtEmissao.setEnabled(true);
               jtfDtEmissao.requestFocus();
           }
               
       }    
    }//GEN-LAST:event_jtfDescricaoKeyPressed

    private void jtfDtEmissaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDtEmissaoKeyPressed
         if (evt.getKeyCode() == evt.VK_ENTER){
           if (jtfDtEmissao.getText().equals("")){
               JOptionPane.showMessageDialog(null, "O campo Data de Emissão não pode ficar em branco");
               return;
           }else{
               jtfNumDoc.setEnabled(true);
               jtfNumDoc.requestFocus();
           }
               
       } 
    }//GEN-LAST:event_jtfDtEmissaoKeyPressed

    private void jtfNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumDocKeyPressed
         if (evt.getKeyCode() == evt.VK_ENTER){
            jcbFornecedor.setEnabled(true);
            jcbFornecedor.requestFocus();             
       } 
    }//GEN-LAST:event_jtfNumDocKeyPressed

    private void jcbFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbFornecedorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
           if (jcbFornecedor.getSelectedIndex() == -1){
               JOptionPane.showMessageDialog(null, "O fornecedor precisa ser preenchido");
               return;
           }        
            
           SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); //você pode usar outras máscaras 
           Date y = new Date();
           jtfDtVencimento.setText(sdf.format(y));
           jtfDtVencimento.setEnabled(true);
           jtfDtVencimento.requestFocus();
        }
    }//GEN-LAST:event_jcbFornecedorKeyPressed

    private void jtfDtVencimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDtVencimentoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfDtVencimento.getText().equals("")){
                JOptionPane.showMessageDialog(null, "O campo Vencimento não pode ficar em branco");
                return;
            }else{
                jtfQtdeParcelas.setEnabled(true);
                jtfQtdeParcelas.requestFocus();
            }
        }
    }//GEN-LAST:event_jtfDtVencimentoKeyPressed

    private void jtfJurosCabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfJurosCabKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfJurosCab.getText().equals(""))
                jtfJurosCab.setText("0,0");
            jtfDescontoCab.setEnabled(true);
            jtfDescontoCab.requestFocus();
        }
    }//GEN-LAST:event_jtfJurosCabKeyPressed

    private void jtfDescontoCabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoCabKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfDescontoCab.getText().equals(""))
                jtfDescontoCab.setText("0,0");
            
            jtfVlTotal.setEnabled(true);
            jtfVlTotal.requestFocus();
        }
    }//GEN-LAST:event_jtfDescontoCabKeyPressed

    private void jtfQtdeParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQtdeParcelasKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfQtdeParcelas.getText().equals("") || jtfQtdeParcelas.getText().equals("0"))
                jtfQtdeParcelas.setText("1");
            jtfSubTotal.setEnabled(true);
            jtfSubTotal.requestFocus();
        }
    }//GEN-LAST:event_jtfQtdeParcelasKeyPressed

    private void jtfSubTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSubTotalKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfSubTotal.getText().equals("")){
                JOptionPane.showMessageDialog(null, "O campo SubTotal não pode ficar em branco");
                return;             
            }
            String subTotalStr = jtfSubTotal.getText();
            subTotalStr = subTotalStr.replace(",", ".");
            jtfSubTotal.setText(new DecimalFormat("#,##0.00").format(Float.parseFloat(subTotalStr)));
                       
            jtfJurosCab.setEnabled(true);
            jtfJurosCab.requestFocus();           
        }
        
    }//GEN-LAST:event_jtfSubTotalKeyPressed

    private void jcbTipoPagtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbTipoPagtoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jcbTipoPagto.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(null, "O campo Tipo Pagamento não pode ficar em branco");
                return;             
            }
//            if (jcbTipoPagto.getSelectedItem().equals("DINHEIRO"))
//               jcbBanco.setSelectedItem("NENHUM");
//            if (jcbTipoPagto.getSelectedItem().equals("NENHUM"))
//                jcbBanco.setSelectedItem("NENHUM");
            jcbBanco.setEnabled(true);
            jcbBanco.requestFocus();           
        }
    }//GEN-LAST:event_jcbTipoPagtoKeyPressed

    private void jcbBancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbBancoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (operacao == "salvar"){
               jbtSalvar.setEnabled(true);
               jbtSalvar.requestFocus();           
            }else{
                jtfJurosDet.setText("");
                jtfJurosDet.requestFocus();
            }    
        }
    }//GEN-LAST:event_jcbBancoKeyPressed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        
        if (operacao == "salvar"){
            try {
                if (jcbFornecedor.getSelectedIndex()== -1){
                    JOptionPane.showMessageDialog(null, "Fornecedor precisa ser preenchido !!!");
                    return;
                }
                if (jtfQtdeParcelas.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Quantidade de parcelas precisa ser preenchido");
                    return;
                }   
                
                
                pagtoDAO.salvar(carregaObjeto());
                JOptionPane.showMessageDialog(null, "Conta à Pagar, Salva com Sucesso!!!");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Problemas ao Salvar Pagamento! Error:"+ex.getMessage());
            }
        }else
            if (operacao == "alterar"){
                if (!(jtfVlPago.getText().equals("0.0"))&&(jcbTipoPagto.getSelectedItem().equals("NENHUM"))){
                    JOptionPane.showMessageDialog(null, "Tipo de Pagamento Inválido");
                    return;
                }
                if (jtfDtPagto.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Data do Pagamento está vazia!!!");
                    jtfDtPagto.requestFocus();
                    return;
                }
                try {
                    alterar();
                }catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Problemas ao Salvar Pagamento! Error:"+ex.getMessage());
                }               
            }
        jbtCancelaActionPerformed(evt);
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jtfSubTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSubTotalKeyTyped
        String caracteres="0987654321,";
        if (!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_jtfSubTotalKeyTyped

    private void jtfJurosCabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfJurosCabKeyTyped
        String caracteres="0987654321,";
        if (!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_jtfJurosCabKeyTyped

    private void jtfDescontoCabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoCabKeyTyped
        String caracteres="0987654321,";
        if (!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_jtfDescontoCabKeyTyped

    private void jbtCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelaActionPerformed
        limpar();
        habilita(false);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setSelectedIndex(0);
        jtfPesquisa.setText("");
        jtfPesquisa.setEnabled(true);
        DefaultTableModel amodel = (DefaultTableModel) jTable2.getModel();
        amodel.setNumRows(0);
        carregaTable();
        jbtNovo.setEnabled(true);
        jbtSalvar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        jbtCancela.setEnabled(false);
        
        jtfPesquisa.requestFocus();
        
    }//GEN-LAST:event_jbtCancelaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        pgtCab = pgtCabDAO.pagamentoCab((Long) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        
        jtfPesquisa.setEnabled(false);
       
        //Carregar Itens da Venda.
        DefaultTableModel amodel = (DefaultTableModel) jTable2.getModel();        
        amodel.setNumRows(0);       
        String vlPg, vlParc, dtpgt;
        for (PagamentoDet pgtDet : pgtCab.getListaPagamentoDet()){
            if (pgtDet.getVl_pago() > 0){
               vlPg = (new DecimalFormat("#,##0.00").format(pgtDet.getVl_pago())); 
               
            }else
                vlPg = "0.0";
            vlParc = (new DecimalFormat("#,##0.00").format(pgtDet.getVl_parcela()));
            if (pgtDet.getDt_pagamento() == null)
                dtpgt = "";
            else
                dtpgt = sdf.format(pgtDet.getDt_pagamento());
            
            
            amodel.addRow(new Object[]{pgtDet.getNum_parcela(), pgtDet.getTipo_pagamento().getDescricao(),pgtDet.getBanco().getDescricao(), String.valueOf(sdf.format(pgtDet.getVencimento())), vlParc, vlPg, dtpgt, pgtDet.getId()});                  
            
            
            
        }      
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centro = new DefaultTableCellRenderer();       
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        centro.setHorizontalAlignment(SwingConstants.CENTER);
             
        //criando o render
        DefaultTableCellRenderer dtcr
                = new DefaultTableCellRenderer() {
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                        String result = (String) table.getValueAt(row, 5);
                        if (result == "0.0") {
                         //   comp.setBackground(Color.RED);
                            comp.setForeground(Color.red);
                        } else {
                         //   comp.setBackground(Color.LIGHT_GRAY);
                            comp.setForeground(Color.blue);
                        }
//                        else {
//                            comp.setBackground(Color.WHITE);
//                            comp.setForeground(Color.BLACK);
//                        }
                        return comp;
                    }
        };
        
        jTable2.setDefaultRenderer(Object.class, dtcr);
      //  jTable2.getColumnModel().getColumn(0).setCellRenderer(centro);
        
        jbtAlterar.setEnabled(false);
        jbtSalvar.setEnabled(false); 
        jbtExcluir.setEnabled(true);
        jbtCancela.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
        operacao = "alterar";
        habilita(true);
        carregaCombobox();
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
        Long id = Long.parseLong(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        pgtCab =  pgtCabDAO.pagamentoCab(id);
        jtfCodigo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jcbFornecedor.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        jtfDescricao.setText(pgtCab.getDescricao());
        jtfDtEmissao.setText(String.valueOf(sdf.format(pgtCab.getEmissao())));
        jtfNumDoc.setText(pgtCab.getNumdoc());
        jtfDtVencimento.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        jtfQtdeParcelas.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        jtfSubTotal.setText(new DecimalFormat("#,##0.00").format(pgtCab.getSubtotal()));
        jtfDescontoCab.setText(String.valueOf(pgtCab.getDesconto()));
        jcbStatus.setSelectedItem(pgtCab.getStatus());
        jtfJurosCab.setText(String.valueOf(pgtCab.getJuro()));     
        jtfVlTotal.setText(new DecimalFormat("#,##0.00").format(pgtCab.getVl_total()));
       
        //Carregar Detalhe de Conta a pagar
        Long idDet = Long.parseLong(jTable2.getValueAt(jTable2.getSelectedRow(), 7).toString());
        pgtDet = pgtCabDAO.pagamentoDet(idDet);
        
          

        jtfNumParcela.setText(String.valueOf(pgtDet.getNum_parcela()));
        jcbTipoPagto.setSelectedItem(pgtDet.getTipo_pagamento().getDescricao());
        jcbBanco.setSelectedItem(pgtDet.getBanco().getDescricao());
        jcbCategoria.setSelectedItem(pgtCab.getId_categoria().getDescricao());
        
       // jtfDtPagto.setText(String.valueOf(pgtDet.getDt_pagamento()));
        jtfJurosDet.setText(String.valueOf(pgtDet.getJuro()));
        jtfDescontoDet.setText(String.valueOf(pgtDet.getDesconto()));
        jtfMulta.setText(String.valueOf(pgtDet.getMulta()));
        jtfVlParcela.setText(new DecimalFormat("#,##0.00").format(pgtDet.getVl_parcela())); 
        if (pgtDet.getVl_pago() == 0.0){
           jtfVlPago.setText(String.valueOf(pgtDet.getVl_pago())); 
           if (pgtDet.getDt_pagamento() == (null)){
           Date y = new Date();
           jtfDtPagto.setText(sdf.format(y));
        } 
        }else{
           jtfVlPago.setText(new DecimalFormat("#,##0.00").format(pgtDet.getVl_pago()));          
           jtfDtPagto.setText(sdf.format(pgtDet.getDt_pagamento()));
        }   
        jlbSaldoDev.setText("R$ "+((new DecimalFormat("#,##0.00").format(pgtCab.getSaldo_devedor()))));       
        jbtNovo.setEnabled(false);
        jbtAlterar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        jcbTipoPagto.requestFocus();
    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jtfJurosDetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfJurosDetKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if ((jtfJurosDet.getText().equals(""))){                
                jtfJurosDet.setText("0.0");
                jtfDescontoDet.setText("");
                jtfDescontoDet.requestFocus();
            }else{
                float porcentagem = 0, vltotal = 0, vlparcela = 0;
                String vlParc_str;
                porcentagem = Float.parseFloat(jtfJurosDet.getText());
                vlParc_str = jtfVlParcela.getText();
                vlparcela = Float.parseFloat(ValorStrParaFloat(vlParc_str));
                       
                vltotal = (vlparcela +(vlparcela*porcentagem/100));
                
                jtfVlPago.setText("");
                jtfVlPago.setText(new DecimalFormat("#,##0.00").format(vltotal));
                
                
                jtfDescontoDet.setEnabled(false);
                jtfMulta.requestFocus();
            }
                
        }
    }//GEN-LAST:event_jtfJurosDetKeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        jbtAlterar.setEnabled(true);
        jbtExcluir.setEnabled(false);
        jlbSaldoDev.setVisible(true);
        jTable2.setSelectionBackground( new Color(255,230,22) );
    }//GEN-LAST:event_jTable2MouseClicked

    private void jtfMultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMultaKeyPressed
        String vlpg_str, vlparc_str; 
         float vlpago=0, vltotal= 0, multa = 0, vlparcela;
        if (evt.getKeyCode() == evt.VK_ENTER){
            if ((jtfMulta.getText().equals("0.0"))||(jtfMulta.getText().equals(""))){
              //  jtfVlPago.setText(jtfVlParcela.getText());
                if (jtfVlPago.getText().equals("0.0"))
                    jtfVlPago.setText(jtfVlParcela.getText());
                jbtSalvar.requestFocus();
            }else{                
                vlpg_str = jtfVlParcela.getText();
                multa = Float.parseFloat(jtfMulta.getText());
                vlpago = Float.parseFloat(ValorStrParaFloat(vlpg_str));                
                vltotal = (vlpago + multa);
//                   vltotal = (vlpago + multa); vlpg_str =
//                if ((jtfJurosDet.getText().equals("0.0"))||(jtfJurosDet.getText().equals("0")) ){
//                   vlparc_str = jtfVlParcela.getText();
//                   vlparcela = Float.parseFloat(vlparc_str = ValorStrParaFloat(vlparc_str));                    
//                   vltotal = (vlparcela + multa);
//                }else{
//                   vlpg_str = jtfVlPago.getText();
//                   vlpago = Float.parseFloat(vlpg_str = ValorStrParaFloat(vlpg_str));
//                   vltotal = (vlpago + multa);
//                }                
                jtfVlPago.setText("");
                jtfVlPago.setText(new DecimalFormat("#,##0.00").format(vltotal)); 
                jtfDescontoDet.setEnabled(false);
                jbtSalvar.requestFocus();
            }                
        }
    }//GEN-LAST:event_jtfMultaKeyPressed

    private void jtfDescontoDetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoDetKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if ((jtfDescontoDet.getText().equals("")) ){
                jtfDescontoDet.setText("0.0");
                jtfJurosDet.setEnabled(true);
                jtfMulta.setText("");
                jtfMulta.requestFocus();
            }else{
                float porcentagem = 0, vltotal = 0, vlparcela = 0;
                String vlParc_str;
                porcentagem = Float.parseFloat(jtfDescontoDet.getText());
                vlParc_str = jtfVlParcela.getText();
                vlparcela = Float.parseFloat(ValorStrParaFloat(vlParc_str));                       
                vltotal = (vlparcela -(vlparcela*porcentagem/100));                
                jtfVlPago.setText("");
                jtfVlPago.setText(new DecimalFormat("#,##0.00").format(vltotal));               
                jtfJurosDet.setEnabled(false);
                jtfMulta.setEnabled(false);
                jbtSalvar.requestFocus();
            }
                
        }
    }//GEN-LAST:event_jtfDescontoDetKeyPressed

    private void jtfDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescricaoFocusLost
        jtfDescricao.setText(jtfDescricao.getText().toUpperCase());
    }//GEN-LAST:event_jtfDescricaoFocusLost

    private void jtfJurosDetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfJurosDetKeyTyped
        String caracteres="0987654321.";
        if (!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_jtfJurosDetKeyTyped

    private void jtfDescontoDetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoDetKeyTyped
        String caracteres="0987654321.";
        if (!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_jtfDescontoDetKeyTyped

    private void jtfMultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMultaKeyTyped
        String caracteres="0987654321.";
        if (!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_jtfMultaKeyTyped

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
       // PagamentoCabDAO pagtoDAO = new PagamentoCabDAO();
        Long id = (Long) (jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        
        if (jTable2.getRowCount() > 0){
            String vlPago;
            for (int i = 0; i < jTable2.getRowCount(); i++){
                vlPago = jTable2.getValueAt(i, 5).toString();                
                if (vlPago == "0.0"){
                    if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir esta Conta à Pagar?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
                       pgtCabDAO.excluirPagamento(id);
                       JOptionPane.showMessageDialog(null, "Conta à Pagar Excluida com Sucesso!!!");
                       jbtCancelaActionPerformed(evt);
                    }
                }else
                    JOptionPane.showMessageDialog(null, "Você não pode excluir esta Conta. Já têm uma parcela Paga.");
                break;
            }           
        }else{
              if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir esta Conta à Pagar?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
                 pgtCabDAO.excluirPagamento(id);
                 JOptionPane.showMessageDialog(null, "Conta à Pagar Excluida com Sucesso!!!");
                 jbtCancelaActionPerformed(evt);
              }
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jtfVlTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfVlTotalKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfVlTotal.getText().equals(""))
                jtfVlTotal.setText(jtfSubTotal.getText());
            else{
                
                String TotalStr = jtfVlTotal.getText();
                TotalStr = TotalStr.replace(",", ".");
                jtfVlTotal.setText(new DecimalFormat("#,##0.00").format(Float.parseFloat(TotalStr)));
            }
            
            jbtSalvar.setEnabled(true);
            jbtSalvar.requestFocus();
                
            
            
        }
    }//GEN-LAST:event_jtfVlTotalKeyPressed

    private void jcbCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbCategoriaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jcbCategoria.getSelectedIndex() > -1){
                jtfDescricao.setEnabled(true);
                jtfDescricao.requestFocus();
            }
        }
    }//GEN-LAST:event_jcbCategoriaKeyPressed

    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
                jbtSalvarActionPerformed(null);
        }  
        
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jbtNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtNovoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtNovoActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtNovoKeyPressed

    private void jbtAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtAlterarKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtAlterarActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtAlterarKeyPressed

    private void jbtCancelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtCancelaKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtCancelaActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtCancelaKeyPressed

    private void jbtExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtExcluirKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtExcluirActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtExcluirKeyPressed

    private void jbtSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSairKeyPressed

       if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtSairActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtSairKeyPressed

    private PagamentoCab carregaObjeto() throws ParseException{
        PagamentoCab pagtoCab = new PagamentoCab();
        PagamentoDet pagtoDet = new PagamentoDet();
        List<PagamentoDet> listPagtoDet = new ArrayList<PagamentoDet>();
        Calendar calendar = Calendar.getInstance(); 
        float vlParcela=0;            
        if (operacao == "salvar"){
           pagtoCab.setDescricao(jtfDescricao.getText());
           SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
           pagtoCab.setEmissao(sdf.parse(jtfDtEmissao.getText()));
           pagtoCab.setNumdoc(jtfNumDoc.getText());
           pagtoCab.setFornecedor(listFornecedor.get(jcbFornecedor.getSelectedIndex()));
           pagtoCab.setVencimento(sdf.parse(jtfDtVencimento.getText()));
           pagtoCab.setStatus(jcbStatus.getSelectedItem().toString());
           pagtoCab.setQtd_parcela(Integer.parseInt(jtfQtdeParcelas.getText()));
           pagtoCab.setSubtotal(Float.parseFloat(ValorStrParaFloat(jtfSubTotal.getText())));
           
           pagtoCab.setDesconto(Float.parseFloat(ValorStrParaFloat(jtfDescontoCab.getText())));
           pagtoCab.setJuro(Float.parseFloat(ValorStrParaFloat(jtfJurosCab.getText())));          
           pagtoCab.setVl_total(Float.parseFloat(ValorStrParaFloat(jtfVlTotal.getText())));            
           vlParcela = (pagtoCab.getVl_total()/pagtoCab.getQtd_parcela());           
        
           //Salvando Categoria Conta
           pagtoCab.setId_categoria(listCategoriaConta.get(jcbCategoria.getSelectedIndex()));
                   
           if (pagtoCab.getQtd_parcela()!= 0){
               calendar.setTime(pagtoCab.getVencimento());               
               for (int i = 1; i <= pagtoCab.getQtd_parcela(); i ++){
                  
                   if (jcbTipoPagto.getSelectedIndex() == -1){
                       jcbTipoPagto.setSelectedItem("NENHUM");
                       pagtoDet.setTipo_pagamento(listTipoPagto.get(jcbTipoPagto.getSelectedIndex()));
                   }else
                       pagtoDet.setTipo_pagamento(listTipoPagto.get(jcbTipoPagto.getSelectedIndex()));
                   if (jcbBanco.getSelectedIndex() == -1){
                       jcbBanco.setSelectedItem("NENHUM");
                       pagtoDet.setBanco(listBanco.get(jcbBanco.getSelectedIndex()));
                   }else
                       pagtoDet.setBanco(listBanco.get(jcbBanco.getSelectedIndex()));
                   
                   pagtoDet.setJuro(0);
                   pagtoDet.setDesconto(0);
                   pagtoDet.setDt_pagamento(null);
                   pagtoDet.setMulta(0);
                   pagtoDet.setNum_parcela(i);
                   pagtoDet.setVencimento(calendar.getTime());
                   pagtoDet.setVl_parcela(vlParcela); 
                   
                   listPagtoDet.add(new PagamentoDet(pagtoDet.getTipo_pagamento(),pagtoDet.getBanco(), pagtoDet.getDesconto(),
                   pagtoDet.getJuro(), pagtoDet.getMulta(), pagtoDet.getVl_parcela(), pagtoDet.getVl_pago(),
                   pagtoDet.getNum_parcela(), pagtoDet.getVencimento(), pagtoDet.getDt_pagamento()));
                   calendar.add(Calendar.MONTH, 1);
                   pagtoDet.setVencimento(calendar.getTime());
               }
               pagtoCab.setListaPagamentoDet(listPagtoDet);
           }
           pagtoCab.setSaldo_devedor(pagtoCab.getVl_total());          
        }
            
        return pagtoCab;
    }
    public void alterar() throws ParseException{
        Calendar calendar = Calendar.getInstance();
        
        if (operacao == "alterar"){
                String vlpg_str = jtfVlPago.getText();
                vlpg_str = ValorStrParaFloat(vlpg_str);
                String vlparc_str = jtfVlParcela.getText();
                vlparc_str = ValorStrParaFloat(vlparc_str);
                calendar.setTime(pgtDet.getVencimento());
                pgtCab.setId_categoria(listCategoriaConta.get(jcbCategoria.getSelectedIndex()));
                pgtCab.setDescricao(jtfDescricao.getText());
                
                
                
                
                pgtDet.setTipo_pagamento(listTipoPagto.get(jcbTipoPagto.getSelectedIndex()));
                pgtDet.setBanco(listBanco.get(jcbBanco.getSelectedIndex()));
                pgtDet.setJuro(Float.parseFloat(jtfJurosDet.getText()));
                pgtDet.setDesconto(Float.parseFloat(jtfDescontoDet.getText()));
                pgtDet.setVencimento(sdf.parse(jtfDtVencimento.getText()));
                
                pgtDet.setVl_parcela(Float.parseFloat(vlparc_str));
                
                if (jtfMulta.getText().equals(""))
                    pgtDet.setMulta(0);
                else
                    pgtDet.setMulta(Float.parseFloat(jtfMulta.getText()));                   
                pgtDet.setVl_pago(Float.parseFloat(vlpg_str));
                pgtDet.setVl_parcela(Float.parseFloat(vlparc_str));
                
                
                Banco bc = new Banco();
                BancoMovimento bm = new BancoMovimento();
                BancoMovimentoDAO bmDAO = new BancoMovimentoDAO();
                bc = listBanco.get(jcbBanco.getSelectedIndex());
                  
                if (!jcbTipoPagto.getSelectedItem().equals("NENHUM") && (!jcbBanco.getSelectedItem().equals("NENHUM")))
                   if (bc.getBancoMovimentoList().isEmpty()){
                      JOptionPane.showMessageDialog(null, "Esta Conta não têm Movimentação !!!");
                      return;                   
                    }
                
                
                
                if (pgtDet.getVl_pago() > 0){                    
                       pgtDet.setDt_pagamento(sdf.parse(jtfDtPagto.getText()));
                       pgtCab.setSaldo_devedor((pgtCab.getSaldo_devedor())-(pgtDet.getVl_parcela()));                    
                       if (jTable2.getRowCount() ==  Integer.parseInt(jtfNumParcela.getText())){
                           JOptionPane.showMessageDialog(null, "Parabéns você está pagando a Última Parcela.");
                           pgtCab.setVencimento(calendar.getTime());
                           pgtCab.setStatus("FECHADO");
                       }else{                    
                           calendar.add(Calendar.MONTH, 1);
                           pgtCab.setVencimento(calendar.getTime());
                       }
                        //Adicionar Debito em Conta Corrente
                        int ultimoRegistro = 0;
                        BigDecimal saldo;
                        BigDecimal debito;
                        ultimoRegistro = bc.getBancoMovimentoList().size();
                        ultimoRegistro = (ultimoRegistro -1);
               
                        saldo = bc.getBancoMovimentoList().get(ultimoRegistro).getSaldo();
                        debito = new BigDecimal(vlpg_str);
                     
                        //Subtrair Debito                   
                        saldo = (saldo.subtract(debito));
                    
                        bm.setIdBanco(bc);
                        bm.setVlSaida(debito);
                        bm.setSaldo(saldo);
                        bm.setObs("Conta:"+jtfCodigo.getText()+" Nº Parc. ("+jtfNumParcela.getText()+") - "+jtfDescricao.getText());
                        bm.setDtLancamento(sdf.parse(jtfDtPagto.getText()));
                        bmDAO.salvar(bm);         
                       
                }
                
               
          //      if (!jcbTipoPagto.getSelectedItem().equals("NENHUM")){
                    
                                      
                    
                         

                pagtoDAO.alterar(pgtCab, pgtDet);
                JOptionPane.showMessageDialog(null, "Conta à Pagar, Alterada com Sucesso!!!");
                
                
                
            }
    } 
    
    
    private String ValorStrParaFloat(String valor){
        valor = valor.replace(".", "");
        valor = valor.replace(",", ".");
        return valor;        
    }
            
    
    
    private void carregaCombobox(){
        fornecedorDAO = new FornecedorDAO();          
        tipoPagtoDAO = new TipoPagamentoDAO();
        categoriaContaDAO = new CategoriaContaDAO();
        bancoDAO = new BancoDAO();
        listFornecedor = fornecedorDAO.listaFornecedor();
        listTipoPagto = tipoPagtoDAO.listTipoPag();
        listBanco = bancoDAO.listBanco();
        listCategoriaConta = categoriaContaDAO.lista();
        
        //Carrega Combobox Fornecedor.
        jcbFornecedor.removeAllItems();
//        for(Pessoa pessao : listFornecedor){
//            System.out.println("Lista fornecedor"+pessao.getId());
//            System.out.println("nome "+pessao.getNome());
//        }
//        
        for (Pessoa fornecedor : listFornecedor){
            jcbFornecedor.addItem(fornecedor.getNome());
        }                     
        jcbTipoPagto.removeAllItems();
        for (TipoPagamento tipoPagto : listTipoPagto){
            jcbTipoPagto.addItem(tipoPagto.getDescricao());
        }
        jcbBanco.removeAllItems();
        for (Banco banco : listBanco){
            jcbBanco.addItem(banco.getDescricao());
        }
        
        jcbCategoria.removeAllItems();
        for (CategoriaConta cat : listCategoriaConta){
            jcbCategoria.addItem(cat.getDescricao());
        }
    }
    
    
    public void limpar(){
        jtfCodigo.setText("");        
        jtfDescricao.setText("");
        jtfDescontoCab.setText("");
        jtfDescontoDet.setText("");
        jtfDtEmissao.setText("");
        jtfDtVencimento.setText("");
        jtfJurosCab.setText("");
        jtfJurosDet.setText("");
        jtfMulta.setText("");
        jtfNumDoc.setText("");
        jtfNumParcela.setText("");
        jtfQtdeParcelas.setText("");
        jtfSubTotal.setText("");
        jtfVlPago.setText("");
        jtfVlParcela.setText("");
        jtfVlTotal.setText("");  
        jcbBanco.setSelectedIndex(-1);
        jcbTipoPagto.setSelectedIndex(-1);
        jcbFornecedor.setSelectedIndex(-1);
        jcbStatus.setSelectedIndex(-1);
    }
    public void habilita(boolean habilitar){
        jtfCodigo.setEnabled(habilitar);        
        jtfDescricao.setEnabled(habilitar);
        jtfDescontoCab.setEnabled(habilitar);
        jtfDescontoDet.setEnabled(habilitar);
        jtfDtEmissao.setEnabled(habilitar);
        jtfDtPagto.setEnabled(habilitar);
        jtfDtVencimento.setEnabled(habilitar);        
        jtfJurosCab.setEnabled(habilitar);
        jtfJurosDet.setEnabled(habilitar);
        jtfMulta.setEnabled(habilitar);
        jtfNumDoc.setEnabled(habilitar);
        jtfNumParcela.setEnabled(habilitar);
        jtfQtdeParcelas.setEnabled(habilitar);
        jtfSubTotal.setEnabled(habilitar);
        jtfVlPago.setEnabled(habilitar);
        jtfVlParcela.setEnabled(habilitar);
        jtfVlTotal.setEnabled(habilitar);
        jcbStatus.setEnabled(habilitar);
        jcbFornecedor.setEnabled(habilitar);
        jcbTipoPagto.setEnabled(habilitar);
        jcbBanco.setEnabled(habilitar);
        jbtSalvar.setEnabled(habilitar);
        jbtAlterar.setEnabled(habilitar);
        jbtExcluir.setEnabled(habilitar);
        jcbCategoria.setEnabled(habilitar);
        
    }
    private void carregaTable(){
        
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
        
        amodel.setNumRows(0);
        PagamentoCabDAO daoPgtCab = new PagamentoCabDAO();        
        listaPgtCab = null;
        
        listaPgtCab = daoPgtCab.listaPgtCab();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (PagamentoCab pgtCab : listaPgtCab){            
            amodel.addRow(new Object[]{pgtCab.getId(),pgtCab.getNumdoc(), pgtCab.getDescricao(), pgtCab.getFornecedor().getNome(), pgtCab.getQtd_parcela(), String.valueOf(sdf.format(pgtCab.getVencimento())), pgtCab.getVl_total()});                  
        }
        
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
//        
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        centro.setHorizontalAlignment(SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centro);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(centro);
     //   jTable1.getColumnModel().getColumn(6).setCellRenderer(direita);
        
        
        
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PagamentoCabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PagamentoCabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PagamentoCabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PagamentoCabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PagamentoCabView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtCancela;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox jcbBanco;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JComboBox jcbFornecedor;
    private javax.swing.JComboBox jcbStatus;
    private javax.swing.JComboBox jcbTipoPagto;
    private javax.swing.JLabel jlbSaldoDev;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescontoCab;
    private javax.swing.JTextField jtfDescontoDet;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfDtEmissao;
    private javax.swing.JTextField jtfDtPagto;
    private javax.swing.JTextField jtfDtVencimento;
    private javax.swing.JTextField jtfJurosCab;
    private javax.swing.JTextField jtfJurosDet;
    private javax.swing.JTextField jtfMulta;
    private javax.swing.JTextField jtfNumDoc;
    private javax.swing.JTextField jtfNumParcela;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfQtdeParcelas;
    private javax.swing.JTextField jtfSubTotal;
    private javax.swing.JTextField jtfVlPago;
    private javax.swing.JTextField jtfVlParcela;
    private javax.swing.JTextField jtfVlTotal;
    private converter.RowSorterToStringConverter rowSorterToStringConverter1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
