/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import cadastroView.ClienteView;
import conexao.JPAUtil;
import dao.PedidoTrocaPresenteDAO;
import dao.PessoaDAO;
import dao.PessoaFisicaDAO;
import java.awt.Color;
import java.awt.Component;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import menuView.Menu;
import static menuView.Menu.jmenuCliente;
import model.PedidoTrocaPresente;
import model.PedidoTrocaPresenteItens;
import model.PessoaFisica;
import static movimentoView.PedidoView.config;
import net.sf.jasperreports.engine.JRException;
import relatoriosView.ImprimeRelatorio;
import relatoriosView.creditocliente.CreditoCliente;
import util.ValidaCNP;

/**
 *
 * @author daniel
 */
public class PedidoTrocaPresenteView extends javax.swing.JFrame {

    /**
     * Creates new form PedidoTrocaPresenteView
     */
    public static PessoaFisica cliente;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); //você pode usar outras máscaras 
    public static List<PedidoTrocaPresenteItens> listaItens =  new ArrayList<>();
    PedidoTrocaPresenteDAO ptpDAO = new PedidoTrocaPresenteDAO();
    List<PedidoTrocaPresente> listaPedidoTroca = new ArrayList<>();
    PedidoTrocaPresente ptp = new PedidoTrocaPresente();
    PedidoDetalheView pedidoDet;
    String optBt = null;
    PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
    //PessoaFisica pFisica = new PessoaFisica();
    ClienteView cliView = null;
    public PedidoTrocaPresenteView() {
        initComponents();
        listaPedidoTroca = null;
        habilita(false);
        jbtNovo.setEnabled(true);
        cliente = new PessoaFisica();
        config.setTipoPesquisa("CODIGOBARRAS");
      //  jrbCliente.setVisible(false);
      //  jrbConsumidor.setVisible(false);
        
        carregaTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        rowSorterToStringConverter1 = new converter.RowSorterToStringConverter();
        jPanel2 = new javax.swing.JPanel();
        jtfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfData = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtfVlDevolucao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfVlTroca = new javax.swing.JTextField();
        jtfCredito = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfCliente = new javax.swing.JTextField();
        jbtPesquisaCli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##");

            jtfCpf = new javax.swing.JFormattedTextField(cpf);
        }catch(Exception e){
            e.printStackTrace();
        }
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtfCodProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtProdutos = new javax.swing.JButton();
        jrbCliente = new javax.swing.JRadioButton();
        jrbConsumidor = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jbtSair = new javax.swing.JButton();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtCalcular = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();

        rowSorterToStringConverter1.setTable(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolução / Troca de Mercadoria - Presente");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Devolução/Troca de Mercadoria"));

        jtfPesquisa.setNextFocusableComponent(jbtNovo);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), jtfPesquisa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        jtfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "CLIENTE", "CPF", "R$ CRÉDITO/DÉBITO", "STATUS", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setAutoscrolls(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(280);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(0);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DADOS DA TROCA/DEVOLUÇÃO"));

        jLabel3.setText("DATA:");

        jtfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos/Mercadorias"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QTD", "UND", "PRODUTO", "R$  UNIT.", "R$ SUB TOTAL", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(145);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        jLabel4.setText("R$ Valor Devolução");

        jtfVlDevolucao.setEditable(false);
        jtfVlDevolucao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("R$ Valor Troca");

        jtfVlTroca.setEditable(false);
        jtfVlTroca.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVlTrocaActionPerformed(evt);
            }
        });

        jtfCredito.setEditable(false);
        jtfCredito.setBackground(new java.awt.Color(255, 244, 131));
        jtfCredito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setText("R$ Crédito/Débito");

        jLabel1.setText("NOME CLIENTE");

        jtfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfClienteKeyPressed(evt);
            }
        });

        jbtPesquisaCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jbtPesquisaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisaCliActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF");

        jtfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCpfKeyPressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABERTO", "FECHADO" }));

        jLabel7.setText("STATUS");

        jtfCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodProdutoActionPerformed(evt);
            }
        });
        jtfCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodProdutoKeyPressed(evt);
            }
        });

        jLabel8.setText("CÓD. PRODUTO");

        jbtProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jbtProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtProdutosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbCliente);
        jrbCliente.setText("Cliente");
        jrbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbConsumidor);
        jrbConsumidor.setText("Consumidor");
        jrbConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConsumidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfVlDevolucao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtfVlTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPesquisaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jrbCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jrbConsumidor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(200, 200, 200)
                                .addComponent(jLabel2)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52))
                            .addComponent(jtfData))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbCliente)
                            .addComponent(jrbConsumidor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtPesquisaCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfVlDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calculator.png"))); // NOI18N
        jbtCalcular.setText("Calcular");
        jbtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularActionPerformed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        
        dispose();
        Menu.pedidoTrocaPresenteView = null;
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
       jbtCancelarActionPerformed(evt);
       Date y = new Date();
       optBt = "NOVO";
       jtfData.setText(sdf.format(y)); 
       jtfData.setEnabled(true);        
       jrbCliente.setEnabled(true);
       jrbConsumidor.setEnabled(true);
       jrbCliente.setSelected(true);
       jtfCliente.setEnabled(true);
      
       jbtPesquisaCli.setEnabled(true);
       jbtCancelar.setEnabled(true);
       jbtNovo.setEnabled(false);
       jComboBox1.setSelectedIndex(0);
       //jtfCliente.setEditable(f);
       jtfCpf.setEditable(true);
       jtfCpf.setEnabled(true);
       jtfCpf.requestFocus();
       
       
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtPesquisaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisaCliActionPerformed

        PesquisaClienteView pesCli = new PesquisaClienteView(new java.awt.Frame(), true, "PEDIDOTROCA");
        
        pesCli.setLocationRelativeTo(null);
        pesCli.setVisible(true);
        
        
    }//GEN-LAST:event_jbtPesquisaCliActionPerformed

    private void jtfCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCpfKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){            
            String cpf = null;  
            
            
            
            if (jtfCpf.getText().equals("   .   .   -  ")){
                //JOptionPane.showMessageDialog(null, "CPF não pode ficar vazio!!!");
                if (jrbCliente.isSelected() == true){
                    JOptionPane.showMessageDialog(null, "Selecione a Opção Consumidor, para deixar CPF vazio.");
                    return;
                }
                
                
                jtfCpf.setText("00000000000");
                
                listaItens = new ArrayList<>();
                jtfCodProduto.setEnabled(true);
                jbtProdutos.setEnabled(true);
                jtfCodProduto.requestFocus();
           
                
            }else{
            
            cpf = jtfCpf.getText();
            cpf = cpf.replace(".", "");
            cpf = cpf.replace("-", "");
            
            //Valida CPF caso não esteja cadastrado força o cadastro do cliente.
            if (ValidaCNP.isValidCPF(cpf) == false) {
                JOptionPane.showMessageDialog(null, "CPF inválido");
                return;
            }else{
                cliente = pessoaFisicaDAO.verificaSeExisteCPF(cpf);
                
                if (cliente == null){
                    if (javax.swing.JOptionPane.showConfirmDialog(null, "Cliente não Cadastrado. Deseja Cadastrar o Cliente?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
                       if (this.cliView == null)
                       this.cliView = new ClienteView();
                       this.cliView.setVisible(true);
                       jmenuCliente.setEnabled(false);              
                    }else{
                        jrbConsumidor.setSelected(true);
                        jrbConsumidorActionPerformed(null);
                        jtfCodProduto.setEnabled(true);
                        jTable2.setEnabled(true);
                        listaItens = new ArrayList<>();
                        jtfCodProduto.requestFocus();
                    }
                    
                    
                }else{
                      jtfCliente.setText(cliente.getNome());
                      // cliente = pFisica;
                      jtfCodProduto.setEnabled(true);
                      jbtProdutos.setEnabled(true);
                      jTable2.setEnabled(true);
                      listaItens = new ArrayList<>();
                      jtfCodProduto.requestFocus();
                }
            }
            
            }
            

        }
    }//GEN-LAST:event_jtfCpfKeyPressed

    private void jbtProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtProdutosActionPerformed

        
        PesquisaProdutoView pesProduto = new PesquisaProdutoView(new java.awt.Frame(), true, "PEDIDOTROCA");
        
        pesProduto.setVisible(true);
        jbtCancelar.setEnabled(true);
        jbtCalcular.setEnabled(true); 
        jtfCodProduto.setText("");
        
    }//GEN-LAST:event_jbtProdutosActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (evt.getClickCount() == 2) {
            
            String status = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 5);
            
            if (status.equals("TROCA")){
                jTable2.setValueAt("DEVOLVIDO", jTable2.getSelectedRow(), 5);               
            }else
                if (status.equals("DEVOLVIDO")){
                    jTable2.setValueAt("TROCA", jTable2.getSelectedRow(), 5);                   
                   
                }
            jbtCalcular.setEnabled(true);
            jbtSalvar.setEnabled(false);
            
        }  
    }//GEN-LAST:event_jTable2MouseClicked

    private void jtfVlTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVlTrocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVlTrocaActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
       
        PessoaDAO pessoaDAO = new PessoaDAO();
        List<CreditoCliente> listaRel = new ArrayList();
        if (optBt.equals("NOVO"))
           ptp = new PedidoTrocaPresente();
    //    ArrayList<PedidoTrocaPresenteItens> listaItensNovo = new ArrayList<>();
    
          
         if (jtfCliente.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Digite o Nome do Cliente");
               jtfCliente.requestFocus();
               return;
           }
          
    
         if (jrbConsumidor.isSelected() == true)           
            cliente = (PessoaFisica) pessoaDAO.pessoa(1L);
         
           
           ptp.setCliente(cliente);               
           ptp.setCpf(jtfCpf.getText());
        
        try {
            ptp.setDt_cad(sdf.parse(jtfData.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(PedidoTrocaPresenteView.class.getName()).log(Level.SEVERE, null, ex.getMessage());
            ex.printStackTrace();
        }
        ptp.setNomeConsumidor(jtfCliente.getText());
        
        String vldevolucaoStr = jtfVlDevolucao.getText();
        vldevolucaoStr = vldevolucaoStr.replace(".", "");
        vldevolucaoStr = vldevolucaoStr.replace(",", ".");
        ptp.setVl_devolucao(new BigDecimal(vldevolucaoStr));
        
        String vlTrocaStr = jtfVlTroca.getText();
        vlTrocaStr = vlTrocaStr.replace(".", "");
        vlTrocaStr = vlTrocaStr.replace(",", ".");
        ptp.setVl_troca(new BigDecimal(vlTrocaStr));
        
        String vlCreditoStr = jtfCredito.getText();
        vlCreditoStr = vlCreditoStr.replace(".", "");
        vlCreditoStr = vlCreditoStr.replace(",", ".");
        ptp.setCredito(new BigDecimal(vlCreditoStr));
        
        ptp.setStatus(jComboBox1.getSelectedItem().toString());
        
        for (int i = 0; i < jTable2.getRowCount(); i ++){            
            listaItens.get(i).setStatus(jTable2.getValueAt(i, 5).toString());           
        }        
        ptp.setListaTrocaPresenteItens(listaItens);
        if (optBt.equals("NOVO")){
           ptpDAO.salvar(ptp);        
           
           
           CreditoCliente crc = new CreditoCliente();
           for (PedidoTrocaPresenteItens itens : listaItens){
              
              crc.setQtd(itens.getQtd().toString());
              crc.setUnd(itens.getProduto().getUnidade().getSigla());
              crc.setProduto(itens.getProduto().getDescricao());
              crc.setVlUnit(new DecimalFormat("#,##0.00").format(itens.getVlUnit()));
              crc.setVlTotal(new DecimalFormat("#,##0.00").format(itens.getVltotal()));
              crc.setStatus(itens.getStatus());
               
              listaRel.add(new CreditoCliente(crc.getQtd(), crc.getUnd(), crc.getProduto(),
              crc.getVlUnit(), crc.getVlTotal(), crc.getStatus()));
              
           }
           
           
           
        }else
            if (optBt.equals("ALTERAR"))
                ptpDAO.alterar(ptp);
        
        JOptionPane.showMessageDialog(null, "Devolução/Troca efetuada com Sucesso"); 
       
        try {
            
            if (optBt.equals("NOVO")) 
               imprimir(listaRel, jtfVlDevolucao.getText(), jtfVlTroca.getText(), jtfCredito.getText(), jtfCliente.getText(), jtfCpf.getText());
            } catch (JRException ex) {
                Logger.getLogger(PedidoTrocaPresenteView.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        jbtCancelarActionPerformed(evt);
        jbtExcluir.setEnabled(false);
        jbtCancelar.setEnabled(false);
        listaPedidoTroca = null;
       
        this.listaItens = new ArrayList<>();
        carregaTable();
        
        
    }//GEN-LAST:event_jbtSalvarActionPerformed

    
    
    
    
    
    
    
    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        limpar();        
        jbtCalcular.setEnabled(false);
        jbtProdutos.setEnabled(false);
        jtfCliente.setEnabled(false);
        jtfCpf.setEnabled(false);
        jtfData.setEnabled(false);
        jbtPesquisaCli.setEnabled(false);
        jbtSalvar.setEnabled(false);
        jbtNovo.setEnabled(true);      
        buttonGroup1.clearSelection();
        jrbCliente.setEnabled(false);
        jrbConsumidor.setEnabled(false);
        jtfVlDevolucao.setEnabled(false);
        jtfVlTroca.setEnabled(false);
        jtfCredito.setEnabled(false);
        carregaTable();
        jbtExcluir.setEnabled(false);
        jbtCancelar.setEnabled(false);
        jtfPesquisa.setText("");
        jtfCodProduto.setEnabled(false);
        jComboBox1.setEnabled(false);
        listaItens = null;
        cliente = null;
        jtfPesquisa.requestFocus();
        
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalcularActionPerformed
      
        String status = null;
        double somaDev = 0;
        double subtotalDev = 0;
        double somaTroca = 0;
        double subtotalTroca = 0;
        double credito = 0;
        String subTotalStr = null;
        String subTotalDevStr = null;
        for (int i = 0; i < jTable2.getRowCount(); i++) {             
            status = (String) jTable2.getValueAt(i, 5);
            if (status.equals("DEVOLVIDO")){
                subTotalDevStr = (jTable2.getValueAt(i, 4).toString());
                subTotalDevStr = subTotalDevStr.replace(".", "");
                subTotalDevStr = subTotalDevStr.replace(",", ".");                
                subtotalDev = Double.parseDouble(subTotalDevStr);
                
                somaDev = (somaDev + subtotalDev);                
            }else
                if (status.equals("TROCA")){
                   subTotalStr = jTable2.getValueAt(i, 4).toString();                
                   subTotalStr = subTotalStr.replace(".", "");
                   subTotalStr = subTotalStr.replace(",", ".");
                   subtotalTroca = Double.parseDouble(subTotalStr);
                   somaTroca = (somaTroca + subtotalTroca);
                }           
        }
        credito = (somaDev - somaTroca);
        jtfVlDevolucao.setText(new DecimalFormat("#,##0.00").format(somaDev));
        jtfVlTroca.setText(new DecimalFormat("#,##0.00").format(somaTroca));
        jtfCredito.setText(new DecimalFormat("#,##0.00").format(credito)); 
        jtfVlDevolucao.setEnabled(true);
        jtfVlTroca.setEnabled(true);
        jtfCredito.setEnabled(true);
        jbtSalvar.setEnabled(true);

    }//GEN-LAST:event_jbtCalcularActionPerformed

    private void jtfClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClienteKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
           
           if (jtfCliente.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Digite o Nome do Consumidor");
               return;
           } 
            jtfCliente.setText(jtfCliente.getText().toUpperCase());
            jtfCpf.setEditable(true);
            jtfCpf.setEnabled(true);
            jtfCpf.requestFocus();            
            
            
        }
    }//GEN-LAST:event_jtfClienteKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Long id = (Long) jTable1.getValueAt(jTable1.getSelectedRow(), 5); 
        DefaultTableModel amodel = (DefaultTableModel) jTable2.getModel(); 
        amodel.setNumRows(0);
         for (PedidoTrocaPresente ptp : listaPedidoTroca){
            if (id == ptp.getId()){  
               optBt = "ALTERAR"; 
               if (ptp.getCliente().getId() == 1)
                   jrbConsumidor.setSelected(true);
               else
                   jrbCliente.setSelected(true);
               
               jtfData.setText(sdf.format(ptp.getDt_cad()));
               jtfCliente.setText(ptp.getNomeConsumidor());
               jtfCpf.setText(ptp.getCpf());
               jComboBox1.setSelectedItem(ptp.getStatus());
               
               for (PedidoTrocaPresenteItens ptpi : ptp.getListaTrocaPresenteItens()){               
                  amodel.addRow(new Object[]{ptpi.getQtd(), ptpi.getProduto().getUnidade().getSigla(),
                  ptpi.getProduto().getDescricao(), new DecimalFormat("#,##0.00").format(ptpi.getVlUnit()),
                  new DecimalFormat("#,##0.00").format(ptpi.getVltotal()), ptpi.getStatus()});                 
               }
               jtfVlDevolucao.setText(new DecimalFormat("#,##0.00").format(ptp.getVl_devolucao()));
               jtfVlTroca.setText(new DecimalFormat("#,##0.00").format(ptp.getVl_troca()));
               jtfCredito.setText(new DecimalFormat("#,##0.00").format(ptp.getCredito()));
               
               
               jComboBox1.setEnabled(true);
               jtfCliente.setEnabled(true);
               jtfCliente.setEditable(false);
               jtfData.setEditable(false);
               jtfCpf.setEditable(false);
               jtfVlDevolucao.setEditable(false);
               jtfVlTroca.setEditable(false);
               jtfCredito.setEditable(false);
               jtfVlDevolucao.setEnabled(true);
               jtfVlTroca.setEnabled(true);
               jtfCredito.setEnabled(true);
               
               jtfData.setEnabled(true);
               jtfCpf.setEnabled(true);
               jbtSalvar.setEnabled(true);
               jbtExcluir.setEnabled(true); 
               jbtCancelar.setEnabled(true);
               jbtNovo.setEnabled(false);
               jbtProdutos.setEnabled(false);
               jbtCalcular.setEnabled(false);               
               jTable2.setEnabled(false);
               
               this.ptp = ptp;
               this.cliente = (PessoaFisica) ptp.getCliente();
                
               this.listaItens = this.ptp.getListaTrocaPresenteItens();
               break;
            }
             
         }
    }//GEN-LAST:event_jTable1MouseClicked

    private void imprimir(List<CreditoCliente> lista, String vlDev, String vlTroca,
            String vlCredito, String nome, String cpf) throws JRException{
        
        ImprimeRelatorio imprimir = new ImprimeRelatorio();
        
        imprimir.creditoCliente(lista, vlDev, vlTroca, vlCredito, nome, cpf);
        
        
    }
    
    
    
    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        
        PedidoTrocaPresenteDAO ptpDao = new PedidoTrocaPresenteDAO();
        
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir a Troca/Devolução de Mercadoria?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            ptpDao.excluir(ptp);
            JOptionPane.showMessageDialog(null, "Troca/Devolução de Mercadoria excluida com Sucesso !!!");       
            listaPedidoTroca = null;
            carregaTable();
            jbtCancelarActionPerformed(evt);
        }
        
        
       
        
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jtfCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodProdutoActionPerformed

    private void jtfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataActionPerformed

    private void jtfCodProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodProdutoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
           try{ 
              String codProd = (jtfCodProduto.getText());
              
              
              pedidoDet = new PedidoDetalheView(new java.awt.Frame(), true, codProd, "PEDIDOTROCA", config.getTipoPesquisa());
             // pedidoDet.setTitle("Adicionar ao Pedido");
              pedidoDet.idProduto = (jtfCodProduto.getText());
              pedidoDet.setLocationRelativeTo(null);
            //pedidoDet.setPreferredSize(900, 115).;
            //this.setBounds(0, 0, 970, 650);
            //Redimensiona o formulário pedidoDet.
             //pedidoDet.setBounds(350, 350, 800, 254);
            // pedidoDet.setBounds(350, 350, 850, 280);
             pedidoDet.setVisible(true); 
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, "Produto não encontrado !!!");               
           }
           jtfCodProduto.setText("");
        }
    }//GEN-LAST:event_jtfCodProdutoKeyPressed

    private void jrbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbClienteActionPerformed

        jtfCpf.requestFocus();
    }//GEN-LAST:event_jrbClienteActionPerformed

    private void jrbConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConsumidorActionPerformed

       jtfCpf.setEnabled(true);
       jtfCliente.setEditable(true);
       jtfCliente.requestFocus();
    }//GEN-LAST:event_jrbConsumidorActionPerformed

    
    private void habilita(boolean habilita){         
        jrbCliente.setEnabled(habilita);
        jrbConsumidor.setEnabled(habilita);
        jtfCliente.setEnabled(habilita);
        jtfCpf.setEnabled(habilita);
        //jTable2.setEnabled(habilita);
        jtfVlDevolucao.setEnabled(habilita);
        jtfVlTroca.setEnabled(habilita);
        jtfCredito.setEnabled(habilita);
        jtfData.setEnabled(habilita);
        jtfCodProduto.setEnabled(habilita);
        
        jbtNovo.setEnabled(habilita);
        jbtProdutos.setEnabled(habilita);
        jbtSalvar.setEnabled(habilita);
        jbtExcluir.setEnabled(habilita);
        jbtPesquisaCli.setEnabled(habilita);
        jbtCancelar.setEnabled(habilita);
        jbtCalcular.setEnabled(habilita);
        jComboBox1.setEnabled(habilita);
    }
    private void limpar(){
         DefaultTableModel amodel =  (DefaultTableModel) jTable2.getModel();
         
         amodel.setNumRows(0);
         
         jtfCliente.setText("");
         jtfCpf.setText("");
         jtfVlDevolucao.setText("");
         jtfVlTroca.setText("");
         jtfCredito.setText("");
         jtfData.setText("");
         jrbCliente.setSelected(false);
         jrbConsumidor.setSelected(false);
         jComboBox1.setSelectedIndex(-1);
    }
    
    
    private void carregaTable(){
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();        
        amodel.setNumRows(0); 
        String data = null;
        
        if (listaPedidoTroca == null){            
            listaPedidoTroca = ptpDAO.listaPedidoTrocaPresente();
        }
        
        for (PedidoTrocaPresente pt : listaPedidoTroca){
            
            data = (sdf.format(pt.getDt_cad()));
            amodel.addRow(new Object[]{data, pt.getNomeConsumidor(), pt.getCpf(),
            new DecimalFormat("#,##0.00").format(pt.getCredito()), pt.getStatus(), pt.getId()});
                        
        }
       
          //criando o render
        DefaultTableCellRenderer dtcr
                = new DefaultTableCellRenderer() {
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                        String valorStr = (String) table.getValueAt(row, 3); 
                        double valor = 0;
                        valorStr = valorStr.replace(".", "");
                        valorStr = valorStr.replace(",", ".");
                        
                        valor = Double.parseDouble(valorStr);
                                
                        
                        
                        if (valor < 0) {
                            comp.setForeground(Color.RED);
                        } else
                              if (valor > 0){
                                 comp.setForeground(Color.blue);
                              }else{
                                    comp.setForeground(Color.BLACK);
                                }                      
                        return comp;
                    }
        };
        
        jTable1.setDefaultRenderer(Object.class, dtcr);
        jTable1.setSelectionBackground( new Color(255,230,22) );
        
      
        
        
                                   
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoTrocaPresenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoTrocaPresenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoTrocaPresenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoTrocaPresenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoTrocaPresenteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JButton jbtCalcular;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisaCli;
    private javax.swing.JButton jbtProdutos;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JRadioButton jrbCliente;
    private javax.swing.JRadioButton jrbConsumidor;
    public static javax.swing.JTextField jtfCliente;
    private javax.swing.JTextField jtfCodProduto;
    public static javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfData;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfVlDevolucao;
    private javax.swing.JTextField jtfVlTroca;
    private converter.RowSorterToStringConverter rowSorterToStringConverter1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
