/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.ProdutoDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Produto;

/**
 *
 * @author daniel
 */
public class PedidoDetalheMeiaView extends javax.swing.JDialog {

    /**
     *Esta tela é chamada através do PedidoDetalheView, toda vez que inseri
     * meia pizza, ela é chamada para adicionar o outro sabor.
     * 
     */
    
    List<Produto> listaProduto;
    ProdutoDAO produtoDao;
    public PedidoDetalheMeiaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbProduto = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.black);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Create.png"))); // NOI18N
        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        dispose();       
        PedidoDetalheView.jtfQuantidade.requestFocus();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        
        Produto p = new Produto();
        
        p = listaProduto.get(jcbProduto.getSelectedIndex());
        
        if (!p.getTamanho().equals(PedidoDetalheView.produto.getTamanho())){            
            JOptionPane.showMessageDialog(null, "Tamanho incompatível. Escolha o tamanho certo.");
            return;
        }
       // p.setBeneficiario(listaBeneficiario.get(jcbBeneficiario10.getSelectedIndex()));
        if (p.equals(PedidoDetalheView.produto)){
            JOptionPane.showMessageDialog(null, "Esta Pizza já faz parte do Pedido. Escolha outro sabor.");
            return;
        }
        
//        PedidoDetalheView.jlCodProdMeia.setVisible(true);
//        PedidoDetalheView.jlDescProdMeia.setVisible(true);
//        PedidoDetalheView.jlCodProdMeia.setText(p.getId().toString());
//        PedidoDetalheView.jlDescProdMeia.setText(p.getDescricao());
        
        //Comparando qual Pizza é mais caro. Se é a primeira ou a segunda.
        if (PedidoDetalheView.produto.getVlVenda() < p.getVlVenda())
            PedidoDetalheView.vlPrecoMeiaPizza = p.getVlVenda();
        else
            PedidoDetalheView.vlPrecoMeiaPizza = PedidoDetalheView.produto.getVlVenda();
        
        PedidoDetalheView.jlPreco.setText(new DecimalFormat("#,##0.00").format(PedidoDetalheView.vlPrecoMeiaPizza));
        PedidoDetalheView.jlPreco.setText("R$ "+ PedidoDetalheView.jlPreco.getText());
        
      //  PedidoDetalheView.jrbInteira.setEnabled(false);
        jbtSairActionPerformed(evt);
        
    }//GEN-LAST:event_jbtAddActionPerformed
 private void carregarCombobox(){
         produtoDao = new ProdutoDAO();
         listaProduto = new ArrayList<Produto>();
         float vlVenda = 0;
         
         listaProduto= produtoDao.produtoIdAtivoCategoria(PedidoDetalheView.produto.getCategoria());
         
         jcbProduto.removeAllItems();
         for (Produto catProd : listaProduto){
             jcbProduto.addItem(catProd.getId()+" - "+catProd.getDescricao()+" --------------- "+new DecimalFormat("#,##0.00").format(catProd.getVlVenda()));
//             if (PedidoDetalheView.produto.getTamanho().equals(catProd.getTamanho())){
//                vlVenda = catProd.getVlVenda();
//                jcbProduto.addItem(catProd.getDescricao()+" --------------- "+new DecimalFormat("#,##0.00").format(vlVenda));
         //    }
         }
         
    } 
    
    
    
    
    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PedidoDetalheMeiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PedidoDetalheMeiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PedidoDetalheMeiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PedidoDetalheMeiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                PedidoDetalheMeiaView dialog = new PedidoDetalheMeiaView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtSair;
    private javax.swing.JComboBox<String> jcbProduto;
    // End of variables declaration//GEN-END:variables
}
