/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.BancoDAO;
import dao.BancoMovimentoDAO;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Banco;
import model.BancoMovimento;

/**
 *
 * @author daniel
 */
public class TransferenciaView extends javax.swing.JDialog {

    /**
     * Creates new form TransferenciaView
     */
    List<Banco> listBanco; 
    List<BancoMovimento> listBancoMov;
    BancoMovimento bancoMov;
    BancoMovimentoDAO bancoMovDAO;
     SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    public TransferenciaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbConta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jftfDt_Transferencia = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtSalvar = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlConta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a Conta para Transferência"));

        jcbConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbContaKeyPressed(evt);
            }
        });

        jLabel1.setText("Conta / Banco");

        jLabel2.setText("R$ Valor");

        jtfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorKeyPressed(evt);
            }
        });

        jLabel3.setText("Data Transferência");

        try {
            jftfDt_Transferencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfDt_Transferencia.setText("  /  /    ");
        jftfDt_Transferencia.setToolTipText("Insira uma Data Válida");
        jftfDt_Transferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftfDt_TransferenciaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jftfDt_Transferencia)
                                .addGap(56, 56, 56)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbConta, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfDt_Transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jbtSalvar.setText("OK");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(jbtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta de Origem"));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Conta: ");

        jlConta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlConta.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Saldo:");

        jlSaldo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlSaldo.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlConta)
                    .addComponent(jlSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlConta))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlSaldo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

       BancoMovimento bm = new BancoMovimento();
       BancoMovimento bmTransf = new BancoMovimento();
       bancoMovDAO = new BancoMovimentoDAO();
       Date y = new Date();
       float valor = 0, saldo = 0;
       //saldo = new BigDecimal(BigDecimal.ZERO);
       String valorStr = null, saldoStr = null;
       int ultimoRegistro = 0;
       
        
       if (jtfValor.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Insira um R$ Valor !!!");
          jtfValor.requestFocus();
          return;       
       }
       
       
       
       valorStr = jtfValor.getText();
       
       valor = Float.parseFloat(ValorStrParaFloat(valorStr));
       
       //Registrar o Débito da Conta em Ação
        ultimoRegistro = BancoMovimentoView.listBanco.get(BancoMovimentoView.jcbBanco.getSelectedIndex()).getBancoMovimentoList().size();
        ultimoRegistro = (ultimoRegistro -1);
        saldoStr = String.valueOf(BancoMovimentoView.listBanco.get(BancoMovimentoView.jcbBanco.getSelectedIndex()).getBancoMovimentoList().get(ultimoRegistro).getSaldo());
      //  System.out.println("Saldo Conta em Ação ="+saldoStr);
        saldo = Float.parseFloat(saldoStr);
        saldo = (saldo - valor);
       // System.out.println("Saldo final conta em Acao ="+saldo);
        //Setar a Data.       
        try {            
            bm.setDtLancamento(sdf.parse(jftfDt_Transferencia.getText().toString()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Data Inválida");
            jftfDt_Transferencia.requestFocus();
        }
        bm.setIdBanco(BancoMovimentoView.listBanco.get(BancoMovimentoView.jcbBanco.getSelectedIndex()));
        bm.setVlEntrada(null);
        bm.setVlSaida(new BigDecimal(valor));
        //Setaar o Saldo        
        bm.setSaldo(new BigDecimal(saldo));
        bm.setObs("Transf. de Saldo para Conta: "+jcbConta.getSelectedItem().toString());
        bancoMovDAO.salvar(bm);
        
        String conta = null;
        conta = jcbConta.getSelectedItem().toString();
        carregaCombobox();
        jcbConta.setSelectedItem(conta);
      
      
       //Registrar a transferencia na conta que recebe o valor.        
       try {            
            bmTransf.setDtLancamento(sdf.parse(jftfDt_Transferencia.getText().toString()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Data Inválida");
            jftfDt_Transferencia.requestFocus();
        }
       bmTransf.setIdBanco(listBanco.get(jcbConta.getSelectedIndex()));
       bmTransf.setVlEntrada(new BigDecimal(valor));
       bmTransf.setVlSaida(null);
       bmTransf.setObs("Transf. de Saldo da Conta: "+BancoMovimentoView.jcbBanco.getSelectedItem());
       
       // System.out.println("tamanha da lista para conta credora ="+listBanco.get(jcbConta.getSelectedIndex()).getBancoMovimentoList().size());
       if (listBanco.get(jcbConta.getSelectedIndex()).getBancoMovimentoList().size() == 0){
           bmTransf.setSaldo(new BigDecimal (valor));
       }else
           if (listBanco.get(jcbConta.getSelectedIndex()).getBancoMovimentoList().size() > 0){
               int ultimoReg = 0;
               float saldoCred = 0;
               String saldoCredStr = null;
               ultimoReg = listBanco.get(jcbConta.getSelectedIndex()).getBancoMovimentoList().size();
               ultimoReg = (ultimoReg -1);
               saldoCredStr = String.valueOf(listBanco.get(jcbConta.getSelectedIndex()).getBancoMovimentoList().get(ultimoReg).getSaldo());
              // System.out.println("Saldo C/ credora ="+saldoStr);
               saldoCred = Float.parseFloat(saldoCredStr);
               
               bmTransf.setSaldo(new BigDecimal(saldoCred + valor));
               
           }
        
        // System.out.println("saldo conta credora ="+bmTransf.getSaldo());
        
        bancoMovDAO.salvar(bmTransf);
        
        JOptionPane.showMessageDialog(null, "Saldo Transferido com Sucesso !!!");
        
       // String conta = null;
       // conta = BancoMovimentoView.jcbBanco.getSelectedItem().toString();
       // BancoMovimentoView.carregaCombobox();
       // BancoMovimentoView.jcbBanco.setSelectedItem(conta);
       
       // BancoMovimentoView.amodel.addRow(new Object[]{sdf.format(bm.getDtLancamento()), bm.getVlEntrada(), bm.getVlSaida(), bm.getSaldo(), bm.getObs()});
        jbtSairActionPerformed(null);
        
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jcbContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbContaKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
           jtfValor.requestFocus();
            
            
        }
    }//GEN-LAST:event_jcbContaKeyPressed

    private void jftfDt_TransferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftfDt_TransferenciaKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER){
           Date y = new Date();
           if (jftfDt_Transferencia.getText().equals("  /  /    ")){
               jftfDt_Transferencia.setText("");
               jftfDt_Transferencia.setText(sdf.format(y));
           }  
           jcbConta.requestFocus();
       }
    }//GEN-LAST:event_jftfDt_TransferenciaKeyPressed

    private void jtfValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
           jbtSalvar.requestFocus();
            
        }    
            
    }//GEN-LAST:event_jtfValorKeyPressed

    
    private void carregaCombobox(){      
        BancoDAO bancoDAO = new BancoDAO();
        listBanco = bancoDAO.listBanco();       
     
        jcbConta.removeAllItems();
        for (Banco banco : listBanco){
            jcbConta.addItem(banco.getDescricao());
        }
        
        
    }
    
    private String ValorStrParaFloat(String valor){
        valor = valor.replace(".", "");
        valor = valor.replace(",", ".");
        return valor;        
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TransferenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TransferenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TransferenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TransferenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                TransferenciaView dialog = new TransferenciaView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox<String> jcbConta;
    private javax.swing.JFormattedTextField jftfDt_Transferencia;
    public static javax.swing.JLabel jlConta;
    public static javax.swing.JLabel jlSaldo;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
