/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimentoView;

import dao.TipoPagamentoDAO;
import dao.VendaRecebimentoDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import model.TipoPagamento;
import model.VendaCab;
import model.VendaRecebimento;

/**
 *
 * @author del
 */
public class VendaRecebimentoView extends javax.swing.JDialog {

    /**
     * Creates new form VendaRecebimentoView
     */
    float  restante, soma, troco, vlrecebido, vltotal, subtotal, porcentagem = 0;
    public static int tipoVenda; 
    public static String transacao = "no";
    public static VendaCab venda = new VendaCab();
    Date dtSis = new Date();
    List<TipoPagamento> listaTipoPagto;
    private static DefaultListModel model;
    List<VendaRecebimento> listaVendaRecebimento = new ArrayList<VendaRecebimento>();
    VendaRecebimento vendaRec = new VendaRecebimento();
  //  private VendaRecebimento vendaRecebimento;
    public VendaRecebimentoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaCombobox();
        iniciarJList();
    }

    private void iniciarJList() {
        jcbTipoPagto.setSelectedIndex(0);
        model.clear();
        model.addElement("Tipo Pagamento                  R$ Valor");
        model.addElement("----------------------------------------------------------");
        soma = 0;
        restante = 0;
        troco = 0;
        vlrecebido = 0;
        vltotal = 0;
        subtotal = 0;
        porcentagem = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbTipoPagto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfSubTotal = new javax.swing.JTextField();
        jtfTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfDesconto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        model = new DefaultListModel();
        jList1 = new JList(model);
        jPanel2 = new javax.swing.JPanel();
        jtfRestante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfValorRecebido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DADOS PAGAMENTO"));

        jcbTipoPagto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbTipoPagtoKeyPressed(evt);
            }
        });

        jLabel1.setText("TIPO PAGAMENTO");

        jLabel2.setText("R$ SUBTOTAL");

        jtfSubTotal.setEditable(false);
        jtfSubTotal.setBackground(new java.awt.Color(248, 241, 190));
        jtfSubTotal.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jtfSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfTotal.setEditable(false);
        jtfTotal.setBackground(new java.awt.Color(248, 241, 120));
        jtfTotal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jtfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("R$ TOTAL");

        jLabel5.setText("DESCONTOS");

        jtfDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfDesconto.setEnabled(false);
        jtfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescontoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDescontoKeyTyped(evt);
            }
        });

        jLabel6.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jcbTipoPagto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jcbTipoPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(8, 8, 8)
                        .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.setToolTipText("Fechar Formulário");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jbtSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSairKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setEnabled(false);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtSair)
                .addComponent(jButton1)
                .addComponent(jbtSalvar))
        );

        jList1.setBackground(new java.awt.Color(242, 235, 170));
        jList1.setAutoscrolls(false);
        jList1.setFocusable(false);
        jScrollPane2.setViewportView(jList1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DADOS DE ENTRADA"));

        jtfRestante.setBackground(new java.awt.Color(34, 231, 254));
        jtfRestante.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jtfRestante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText("R$ RECEBIDO");

        jLabel12.setText("R$ Restante");

        jtfValorRecebido.setBackground(new java.awt.Color(82, 82, 229));
        jtfValorRecebido.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jtfValorRecebido.setForeground(java.awt.Color.white);
        jtfValorRecebido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfValorRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfValorRecebidoFocusGained(evt);
            }
        });
        jtfValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorRecebidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorRecebidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jtfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        VendaRecebimentoDAO daoRecebto = new VendaRecebimentoDAO();
        
           
           try{
               
               for (VendaRecebimento v: listaVendaRecebimento){
                   System.out.println("valor ="+v.getVl_recebido());
               }
               
               System.out.println("Tamanho da lista recebimento ="+listaVendaRecebimento.size());
               daoRecebto.salvar(listaVendaRecebimento);
               
               VendaCabView.recebidoStr = String.valueOf(soma);
               VendaCabView.trocoStr = jtfRestante.getText();
               if (listaVendaRecebimento.size() > 1)
                  VendaCabView.tipoPagto = "MULTIPLO";
               if (listaVendaRecebimento.size() == 1)
                   VendaCabView.tipoPagto = jcbTipoPagto.getSelectedItem().toString();
               if (listaVendaRecebimento.size() == 0){
                   JOptionPane.showMessageDialog(null, "Nenhum tipo de Pagamento foi informado para esta Venda.");
                   return;
               }
               transacao = "yes";
           }catch (Exception ex){
               JOptionPane.showMessageDialog(null, "Problemas ao Receber a Venda. Error: "+ex.getMessage());
               transacao = "no";
           }
           dispose();
        
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private VendaRecebimento carregaVendaRecebimento(){
        VendaRecebimento vendaRecebto = new VendaRecebimento();
        
       
        vendaRecebto.setTipoPagamento(listaTipoPagto.get(jcbTipoPagto.getSelectedIndex()));
        vendaRecebto.setDtPagamento(dtSis);
 //       vendaRecebto.setParcela(Integer.parseInt(jlParcela.getText()));
//        vendaRecebto.setJuro(Float.parseFloat(jtfJuros.getText()));
        vendaRecebto.setDesconto(Float.parseFloat((jtfDesconto.getText())));
        vendaRecebto.setVl_subtotal(subtotal);
        vendaRecebto.setVl_total(vltotal);
        vendaRecebto.setVl_recebido(vlrecebido);
        vendaRecebto.setVl_troco(troco);
        vendaRecebto.setVenda(venda);        
        
        if (tipoVenda == 0)//Venda A Vista.
            vendaRecebto.setDtVencimento(dtSis);
        
        return vendaRecebto;           
    }
    
    
    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed
        
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        
        dispose();
       
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSairKeyPressed
        //        if (evt.getKeyCode() == evt.VK_ENTER){
            //            OrcamentoCabView.jtfDesconto.requestFocus();
            //            dispose();
            //        }
    }//GEN-LAST:event_jbtSairKeyPressed

    private void jtfValorRecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorRecebidoKeyTyped
        String caracteres="0987654321,";
        if (!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfValorRecebidoKeyTyped

    private void jtfValorRecebidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorRecebidoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
             //String restante;
             
            if (jtfValorRecebido.getText().equals("")){
                JOptionPane.showMessageDialog(null, "O Valor Recebido não pode ser Vazio !!!");
                jtfValorRecebido.requestFocus();
                return;
            }

            String vlTotalStr = jtfTotal.getText();
            String vlRecebidoStr = jtfValorRecebido.getText();
            String somaStr = null; 
            vlTotalStr = vlTotalStr.replace(".", "");
            vlTotalStr = vlTotalStr.replace(",", ".");
            
            vlRecebidoStr = vlRecebidoStr.replace(".", "");
            vlRecebidoStr = vlRecebidoStr.replace(",", ".");
            
            vltotal = Float.parseFloat(vlTotalStr);
            vlrecebido = Float.parseFloat(vlRecebidoStr);            
            soma = soma + vlrecebido;          
            if (soma < vltotal){
                jtfValorRecebido.setText(new DecimalFormat("#,##0.00").format(vlrecebido));
                imprimirPagamento(jcbTipoPagto.getSelectedItem().toString()); 
                
                vendaRec.setVenda(venda);
                vendaRec.setDesconto(Float.parseFloat(jtfDesconto.getText()));
                vendaRec.setDtPagamento(dtSis);
                vendaRec.setDtVencimento(dtSis);
                vendaRec.setVl_subtotal(subtotal);
                vendaRec.setVl_total(vltotal);
                vendaRec.setVl_recebido(vlrecebido);
                vendaRec.setVl_troco(0);
                vendaRec.setParcela(0);
                vendaRec.setTipoPagamento(listaTipoPagto.get(jcbTipoPagto.getSelectedIndex()));
                
                listaVendaRecebimento.add(new VendaRecebimento(vendaRec.getVenda(), vendaRec.getTipoPagamento(),
                vendaRec.getDesconto(), vendaRec.getDtPagamento(), vendaRec.getDtVencimento(),
                vendaRec.getVl_recebido(), vendaRec.getVl_total(), vendaRec.getVl_subtotal(),
                vendaRec.getVl_troco(), vendaRec.getParcela()));
                
                jtfValorRecebido.setText("");
                restante = (vltotal - soma);
                jtfRestante.setText(new DecimalFormat("#,##0.00").format(restante));
                jcbTipoPagto.requestFocus();
            }else     
               if (soma >= vltotal){
                  String trocoStr = null; 
                  troco = (soma  -  vltotal);
                  trocoStr = String.valueOf(troco);
                  trocoStr = (new DecimalFormat("#,##0.00").format(troco));
                  jtfValorRecebido.setText(new DecimalFormat("#,##0.00").format(vlrecebido));              
                  imprimirPagamento(jcbTipoPagto.getSelectedItem().toString());
                  somaStr = (new DecimalFormat("#,##0.00").format(soma));
                  model.addElement("------------------------------------------------------------");
                  model.addElement("SubTotal:"+"                               "+jtfSubTotal.getText() );
                  model.addElement("Desconto: %"+"                              "+jtfDesconto.getText());
                  model.addElement("Total:"+"                                     "+jtfTotal.getText());
                  model.addElement("Valor Recebido:"+"                     "+somaStr);
                  model.addElement("Troco:"+"                                    "+trocoStr);
                  model.addElement("------------------------------------------------------------");
                  model.addElement("Obrigado e Volte sempre"); 
                  
                  vendaRec.setVenda(venda);
                  vendaRec.setDesconto(Float.parseFloat(jtfDesconto.getText()));
                  vendaRec.setDtPagamento(dtSis);
                  vendaRec.setVl_subtotal(subtotal);
                  vendaRec.setVl_total(vltotal);
                  vendaRec.setVl_recebido(vlrecebido);
                  vendaRec.setVl_troco(troco);
                  vendaRec.setParcela(0);
                  vendaRec.setDtVencimento(dtSis);
                  vendaRec.setTipoPagamento(listaTipoPagto.get(jcbTipoPagto.getSelectedIndex()));
                
                  listaVendaRecebimento.add(new VendaRecebimento(vendaRec.getVenda(), vendaRec.getTipoPagamento(),
                  vendaRec.getDesconto(), vendaRec.getDtPagamento(), vendaRec.getDtVencimento(),
                  vendaRec.getVl_recebido(), vendaRec.getVl_total(), vendaRec.getVl_subtotal(),
                  vendaRec.getVl_troco(), vendaRec.getParcela()));
                                                    
                  restante = (vltotal - soma);
                  jtfRestante.setText(new DecimalFormat("#,##0.00").format(restante));
                  jbtSalvar.setEnabled(true);
                  jbtSalvar.requestFocus();                  
                  
               }            
               
                
            
            
            
            //Fim da venda a vista.

        }

    }//GEN-LAST:event_jtfValorRecebidoKeyPressed

    private void imprimirPagamento(String tipoPg) {
        if (tipoPg.length() == 12)
            model.addElement(tipoPg+"                         "+jtfValorRecebido.getText());
        if (tipoPg.length() == 11)
            model.addElement(tipoPg+"                          "+jtfValorRecebido.getText());
        if (tipoPg.length() == 10)
            model.addElement(tipoPg+"                           "+jtfValorRecebido.getText());
        if (tipoPg.length() == 9)
            model.addElement(tipoPg+"                               "+jtfValorRecebido.getText());
        if (tipoPg.length() == 8)
            model.addElement(tipoPg+"                                "+jtfValorRecebido.getText());
        if (tipoPg.length() == 7)
            model.addElement(tipoPg+"                                 "+jtfValorRecebido.getText());
        if (tipoPg.length() == 6)
            model.addElement(tipoPg+"                                  "+jtfValorRecebido.getText());       
    }

    
    
    private void jtfValorRecebidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfValorRecebidoFocusGained
        jtfValorRecebido.setText("");
    }//GEN-LAST:event_jtfValorRecebidoFocusGained

    private void jtfDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoKeyTyped
        String caracteres="0987654321.";
        if (!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfDescontoKeyTyped

    private void jtfDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            //            // subtotal = vltotal;
            String subtotalStr;
            subtotalStr = jtfSubTotal.getText();
            subtotalStr = subtotalStr.replace(".", "");
            subtotalStr = subtotalStr.replace(",", ".");

            subtotal= Float.parseFloat(subtotalStr);
            if ((jtfDesconto.getText().equals("")) || (jtfDesconto.getText().equals("0"))
                || (jtfDesconto.equals("0.0"))){
                jtfDesconto.setText("");
                jtfDesconto.setText("0");
                vltotal = subtotal;
                jtfTotal.setText(new DecimalFormat("#,##0.00").format(vltotal));

            }else{
                porcentagem = Float.parseFloat(jtfDesconto.getText());
                vltotal = (subtotal -(subtotal*porcentagem/100));
                jtfTotal.setText("");
                jtfTotal.setText(new DecimalFormat("#,##0.00").format(vltotal));
            }
            jtfValorRecebido.requestFocus();
        }
    }//GEN-LAST:event_jtfDescontoKeyPressed

    private void jcbTipoPagtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbTipoPagtoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (!jcbTipoPagto.getSelectedItem().equals("")){
                jtfValorRecebido.requestFocus();
            }
        }
    }//GEN-LAST:event_jcbTipoPagtoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iniciarJList();
        jtfRestante.setText(jtfTotal.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

//    public VendaRecebimento getVendaRecebimento() {
//        return vendaRecebimento;
//    }
//
//    public void setVendaRecebimento(VendaRecebimento vendaRecebimento) {
//        this.vendaRecebimento = vendaRecebimento;
//    }

 private void carregaCombobox(){
        TipoPagamentoDAO tipoDao = new TipoPagamentoDAO();
         //fornecedorDAO = new FornecedorDAO();
        listaTipoPagto = new ArrayList<TipoPagamento>();
        
        listaTipoPagto = tipoDao.listTipoPag();
        jcbTipoPagto.removeAllItems();       

        for (TipoPagamento tpPagto:listaTipoPagto){
            jcbTipoPagto.addItem(tpPagto.getDescricao());           
        }
        jcbTipoPagto.setSelectedIndex(-1);
       
       
    }   
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VendaRecebimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VendaRecebimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VendaRecebimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VendaRecebimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                VendaRecebimentoView dialog = new VendaRecebimentoView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    public static javax.swing.JComboBox jcbTipoPagto;
    public static javax.swing.JTextField jtfDesconto;
    private javax.swing.JTextField jtfRestante;
    public static javax.swing.JTextField jtfSubTotal;
    public static javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfValorRecebido;
    // End of variables declaration//GEN-END:variables
}








