/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroView;


import dao.ColaboradorDAO;

import dao.PessoaContatoDAO;
import dao.PessoaDAO;
import dao.PessoaEnderecoDAO;
import dao.PessoaFisicaDAO;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;


import model.Colaborador;
import model.EstadoCivil;
import model.Pessoa;
import model.PessoaContato;
import model.PessoaEndereco;
import model.PessoaFisica;
import model.PessoaJuridica;
import util.RemoverAcentosString;
import util.ValidaCNP;

/**
 *
 * @author root
 */
public final class ColaboradorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    List<PessoaFisica> listaClienteFisico;
    List<PessoaJuridica> listaClienteJuridico;
    List<Colaborador> listaColaborador;
    public static String operacao;
    String cpf = null;
    String cnpj = null;
    //Variavél para chamar a tela de cadastro de endereco de pessoa
    private EnderecoView enderecoView;
    private ContatoView contatoView;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private Pessoa pessoa;
    Date y = new Date();
    public ColaboradorView() {
        initComponents();
        habilitar(false);
        jTabbedPane1.setEnabled(true);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setSelectedIndex(0);
        jtfPesquisaCliente.setEnabled(true);
        carregaTable();
        jtfPesquisaCliente.requestFocus();
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        rowSorterToStringConverter1 = new converter.RowSorterToStringConverter();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jtfPesquisaCliente = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jrbFisica = new javax.swing.JRadioButton();
        jrbJuridico = new javax.swing.JRadioButton();
        jftfDataCadastro = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfSite = new javax.swing.JTextField();
        jpanelPessoaFisi = new javax.swing.JPanel();
        jpanelPessoaFisica = new javax.swing.JPanel();
        cpfLabel = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##");

            jtfCpf = new javax.swing.JFormattedTextField(cpf);
        }catch(Exception e){
            e.printStackTrace();
        }
        rgLabel = new javax.swing.JLabel();
        jtfRG = new javax.swing.JTextField();
        orgaoRgLabel = new javax.swing.JLabel();
        jtfOrgaoRg = new javax.swing.JTextField();
        cpfLabel1 = new javax.swing.JLabel();
        jcbEstadoCivil = new javax.swing.JComboBox();
        jcbSexo = new javax.swing.JComboBox();
        cpfLabel2 = new javax.swing.JLabel();
        orgaoRgLabel1 = new javax.swing.JLabel();
        jftfDt_EmissaoRG = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/###");

            jftfDt_EmissaoRG = new javax.swing.JFormattedTextField(data);
        }catch(Exception e){
            e.printStackTrace();
        }
        jPanel10 = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        cpfLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jtfSenha = new javax.swing.JPasswordField();
        jtfRedSenha = new javax.swing.JPasswordField();
        cpfLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfDt_Admissao = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDt_Demissao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbTipoUsuario = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jtfUltimoAcesso = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEndereco = new javax.swing.JTable();
        jbtAdicionarEndereco = new javax.swing.JButton();
        jbtExcluirEndereco = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableContato = new javax.swing.JTable();
        jbtAdicionaContato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtNovo = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        rowSorterToStringConverter1.setTable(jTable1);

        setMaximizable(true);
        setTitle("CADASTRO DE COLABORADORES");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Colaborador"));

        jtfPesquisaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfPesquisaCliente.setNextFocusableComponent(jbtNovo);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), jtfPesquisaCliente, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        jtfPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaClienteActionPerformed(evt);
            }
        });
        jtfPesquisaCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPesquisaClienteFocusLost(evt);
            }
        });
        jtfPesquisaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaClienteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtfPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setToolTipText("Cliente");

        jPanel2.setDoubleBuffered(false);
        jPanel2.setEnabled(false);
        jPanel2.setFocusTraversalPolicyProvider(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("IDENTIFICAÇÃO DO CLIENTE"));

        jLabelNome.setText("NOME");

        jLabel6.setText("E-MAIL");

        jLabel7.setText("SITE");

        jtfNome.setEnabled(false);
        jtfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeFocusLost(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jtfEmail.setEnabled(false);
        jtfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEmailFocusLost(evt);
            }
        });
        jtfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEmailKeyPressed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Cliente"));

        buttonGroup2.add(jrbFisica);
        jrbFisica.setText("Física");
        jrbFisica.setNextFocusableComponent(jrbJuridico);
        jrbFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFisicaActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbJuridico);
        jrbJuridico.setText("Jurídica");
        jrbJuridico.setNextFocusableComponent(jtfNome);
        jrbJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbJuridicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbJuridico)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFisica)
                    .addComponent(jrbJuridico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jftfDataCadastro.setEditable(false);
        jftfDataCadastro.setEnabled(false);
        jftfDataCadastro.setFocusable(false);

        jLabel4.setText("DATA CADASTRO");

        jLabel2.setText("CÓDIGO");

        jtfCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCodigo.setEnabled(false);

        jtfSite.setEnabled(false);
        jtfSite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfSiteFocusLost(evt);
            }
        });
        jtfSite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSiteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfSite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jftfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(168, 168, 168))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNome)))
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COLABORADOR", jPanel2);

        jpanelPessoaFisi.setDoubleBuffered(false);
        jpanelPessoaFisi.setEnabled(false);

        jpanelPessoaFisica.setBorder(javax.swing.BorderFactory.createTitledBorder("PESSOA FÍSICA :"));
        jpanelPessoaFisica.setDoubleBuffered(false);

        cpfLabel.setText("CPF ");

        //jtfCpf = DefinirTiposCaracteresETamanho(11, "0,1,2,3,4,5,6,7,8,9");
        jtfCpf.setEnabled(false);
        jtfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCpfFocusLost(evt);
            }
        });
        jtfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCpfKeyPressed(evt);
            }
        });

        rgLabel.setText("RG ");

        jtfRG.setEnabled(false);
        jtfRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfRGFocusLost(evt);
            }
        });
        jtfRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfRGKeyPressed(evt);
            }
        });

        orgaoRgLabel.setText("ORGAO RG  ");

        jtfOrgaoRg.setEnabled(false);
        jtfOrgaoRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfOrgaoRgFocusLost(evt);
            }
        });
        jtfOrgaoRg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfOrgaoRgKeyPressed(evt);
            }
        });

        cpfLabel1.setText("ESTADO CIVIL ");

        jcbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLTEIRO", "CASADO", "UNIAO ESTAVEL", "AMASIADO", "VIUVO" }));
        jcbEstadoCivil.setEnabled(false);
        jcbEstadoCivil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbEstadoCivilFocusLost(evt);
            }
        });
        jcbEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbEstadoCivilKeyPressed(evt);
            }
        });

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMININO" }));
        jcbSexo.setEnabled(false);
        jcbSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbSexoFocusLost(evt);
            }
        });
        jcbSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbSexoKeyPressed(evt);
            }
        });

        cpfLabel2.setText("SEXO");

        orgaoRgLabel1.setText("EMISSÃO RG");

        jftfDt_EmissaoRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jftfDt_EmissaoRG.setEnabled(false);
        jftfDt_EmissaoRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftfDt_EmissaoRGKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpanelPessoaFisicaLayout = new javax.swing.GroupLayout(jpanelPessoaFisica);
        jpanelPessoaFisica.setLayout(jpanelPessoaFisicaLayout);
        jpanelPessoaFisicaLayout.setHorizontalGroup(
            jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPessoaFisicaLayout.createSequentialGroup()
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgLabel))
                .addGap(36, 36, 36)
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelPessoaFisicaLayout.createSequentialGroup()
                        .addComponent(orgaoRgLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpanelPessoaFisicaLayout.createSequentialGroup()
                        .addComponent(jtfOrgaoRg, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbSexo, 0, 161, Short.MAX_VALUE)
                            .addComponent(cpfLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfDt_EmissaoRG))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpanelPessoaFisicaLayout.createSequentialGroup()
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfLabel)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orgaoRgLabel1)
                .addGap(95, 95, 95))
        );
        jpanelPessoaFisicaLayout.setVerticalGroup(
            jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPessoaFisicaLayout.createSequentialGroup()
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfLabel1)
                    .addComponent(cpfLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLabel)
                    .addComponent(orgaoRgLabel)
                    .addComponent(orgaoRgLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOrgaoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfDt_EmissaoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanelPessoaFisiLayout = new javax.swing.GroupLayout(jpanelPessoaFisi);
        jpanelPessoaFisi.setLayout(jpanelPessoaFisiLayout);
        jpanelPessoaFisiLayout.setHorizontalGroup(
            jpanelPessoaFisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelPessoaFisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelPessoaFisiLayout.setVerticalGroup(
            jpanelPessoaFisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPessoaFisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DOCUMENTOS", jpanelPessoaFisi);

        jPanelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("DADOS COLABORADOR"));
        jPanelLogin.setAlignmentX(0.0F);
        jPanelLogin.setAlignmentY(0.0F);

        cpfLabel5.setText("SENHA");

        jLabel1.setText("LOGIN");

        jtfLogin.setEnabled(false);
        jtfLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfLoginFocusLost(evt);
            }
        });
        jtfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfLoginKeyPressed(evt);
            }
        });

        jtfSenha.setEnabled(false);
        jtfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSenhaKeyPressed(evt);
            }
        });

        jtfRedSenha.setEnabled(false);
        jtfRedSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfRedSenhaKeyPressed(evt);
            }
        });

        cpfLabel6.setText("REDIGITE A SENHA");

        jLabel3.setText("DATA  ADMISSÃO");

        jtfDt_Admissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jtfDt_Admissao.setEnabled(false);
        jtfDt_Admissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDt_AdmissaoKeyPressed(evt);
            }
        });

        jLabel5.setText("DATA DEMISSÃO");

        jtfDt_Demissao.setEnabled(false);
        jtfDt_Demissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDt_DemissaoKeyPressed(evt);
            }
        });

        jLabel8.setText("TIPO DE USUÁRIO");

        jcbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN", "COLABORADOR" }));
        jcbTipoUsuario.setSelectedIndex(-1);
        jcbTipoUsuario.setEnabled(false);
        jcbTipoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbTipoUsuarioKeyPressed(evt);
            }
        });

        jLabel9.setText("ÚLTIMO ACESSO");

        jtfUltimoAcesso.setEnabled(false);

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(192, 192, 192)
                                .addComponent(jLabel3))
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jtfDt_Admissao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cpfLabel6)
                                    .addComponent(jtfRedSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jtfUltimoAcesso))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfDt_Demissao)))
                    .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel5)
                    .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDt_Admissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDt_Demissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUltimoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfLabel5)
                    .addComponent(cpfLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRedSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LOGIN", jPanel10);

        jTableEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LOGRADOURO", "NUMERO", "BAIRRO", "CIDADE", "UF", "CEP", "PRINCIPAL", "CORRESPONDENCIA", "ENTREGA", "COBRANCA", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEndereco.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnderecoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEndereco);
        if (jTableEndereco.getColumnModel().getColumnCount() > 0) {
            jTableEndereco.getColumnModel().getColumn(0).setPreferredWidth(180);
            jTableEndereco.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableEndereco.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTableEndereco.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableEndereco.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTableEndereco.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTableEndereco.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTableEndereco.getColumnModel().getColumn(7).setPreferredWidth(50);
            jTableEndereco.getColumnModel().getColumn(8).setPreferredWidth(50);
            jTableEndereco.getColumnModel().getColumn(10).setPreferredWidth(10);
        }

        jbtAdicionarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbtAdicionarEndereco.setText("Adicionar Endereço");
        jbtAdicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAdicionarEnderecoActionPerformed(evt);
            }
        });
        jbtAdicionarEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtAdicionarEnderecoKeyPressed(evt);
            }
        });

        jbtExcluirEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbtExcluirEndereco.setText("Excluir Endereço");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableEndereco, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jbtExcluirEndereco, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbtExcluirEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirEnderecoActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Next.png"))); // NOI18N
        jButton2.setText("Próximo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jbtAdicionarEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluirEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtAdicionarEndereco)
                        .addComponent(jbtExcluirEndereco))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ENDEREÇOS", jPanel6);

        jTableContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRIÇÃO", "DDD", "NÚMERO", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableContato.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTableContato);
        if (jTableContato.getColumnModel().getColumnCount() > 0) {
            jTableContato.getColumnModel().getColumn(0).setResizable(false);
            jTableContato.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableContato.getColumnModel().getColumn(1).setResizable(false);
            jTableContato.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTableContato.getColumnModel().getColumn(2).setResizable(false);
            jTableContato.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableContato.getColumnModel().getColumn(3).setResizable(false);
            jTableContato.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jbtAdicionaContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbtAdicionaContato.setText("Adicionar Contato");
        jbtAdicionaContato.setNextFocusableComponent(jbtSalvar);
        jbtAdicionaContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAdicionaContatoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jButton1.setText("Excluir Contato");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableContato, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jbtAdicionaContato, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtAdicionaContato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONTATOS", jPanel9);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });
        jbtNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtNovoKeyPressed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setEnabled(false);
        jbtExcluir.setFocusCycleRoot(true);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.setEnabled(false);
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });
        jbtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtCancelarKeyPressed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setEnabled(false);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jbtSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSairKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtExcluir)
                .addComponent(jbtSair))
            .addComponent(jbtNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPesquisaClienteFocusLost
        // TODO add your handling code here:
        // btnNovo.requestFocus();
        //  jbtNovo.requestFocus();
    }//GEN-LAST:event_jtfPesquisaClienteFocusLost

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        // TODO add your handling code here:
        operacao = "salvar";
        jbtCancelarActionPerformed(evt);
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
        amodel.setNumRows(0);
        jftfDataCadastro.setEnabled(true);
        jftfDataCadastro.setEditable(false);
        SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy"); //você pode usar outras máscaras 
        Date y = new Date();
        jftfDataCadastro.setValue(y);
   //     jcbTipoCliente.setEnabled(true);
        // jTabbedPane1.setEnabled(true);
        jrbFisica.setSelected(true);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
        jPanelLogin.setVisible(false);
        jTabbedPane1.setSelectedIndex(0);
        jbtCancelar.setEnabled(true);
        jbtNovo.setEnabled(false);

        jtfPesquisaCliente.setEnabled(false);
        jtfNome.setEnabled(true);
        jrbFisica.setEnabled(true);
        jrbJuridico.setEnabled(true);
        jpanelPessoaFisi.setEnabled(true);
        jtfNome.requestFocus();

    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        // TODO add your handling code here:
        dispose();
       // jbtCancelarActionPerformed(evt);
        menuView.Menu.jbtClientes.setEnabled(true);
     //   menuView.Principal.jbtClientes.requestFocus();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed

        habilitar(false);
        jTabbedPane1.setSelectedIndex(0);
        jbtNovo.setEnabled(true);

        jtfPesquisaCliente.setEnabled(true);
        jtfPesquisaCliente.requestFocus();

        //Limpar jTableEndereco
        DefaultTableModel amodel = (DefaultTableModel) jTableEndereco.getModel();
        amodel.setNumRows(0);
        //Limpar jTableContato
        DefaultTableModel amodel1 = (DefaultTableModel) jTableContato.getModel();
        amodel1.setNumRows(0);
        
        DefaultTableModel amodel2 = (DefaultTableModel) jTable1.getModel();
        amodel2.setNumRows(0);
        limpar();

        jbtSalvar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        jbtCancelar.setEnabled(false);
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jtfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusLost
        jtfEmail.setText(jtfEmail.getText().toLowerCase());

    }//GEN-LAST:event_jtfEmailFocusLost

    private void jtfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeFocusLost
        // TODO add your handling code here:
        //jtfNome.setText(jtfNome.getText().toUpperCase());
         jtfNome.setText(RemoverAcentosString.semAcento(jtfNome.getText().toUpperCase()));

    }//GEN-LAST:event_jtfNomeFocusLost

    private void jtfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCpfFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_jtfCpfFocusLost

    private void jcbEstadoCivilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbEstadoCivilFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jcbEstadoCivilFocusLost

    private void jtfRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRGFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfRGFocusLost

    private void jtfOrgaoRgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfOrgaoRgFocusLost
        // TODO add your handling code here:
        jtfOrgaoRg.setText(jtfOrgaoRg.getText().toUpperCase());

    }//GEN-LAST:event_jtfOrgaoRgFocusLost

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        try {
            // TODO add your handling code here:
            salvar();
            
            // jbtCancelarActionPerformed(evt);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Problemas ao Salvar Colaborador");
        }

    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_jtfNomeKeyTyped

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {

            if (jtfNome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "O campo nome não pode ser vazio ou nullo!!!");
                jtfNome.requestFocus();
            } else {
                jtfEmail.setEnabled(true);
                jbtSalvar.setEnabled(true);
                jtfEmail.requestFocus();
            }

        }
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEmailKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {

            if (jtfEmail.getText().equals("")) {

                jtfSite.setEnabled(true);
                jtfSite.requestFocus();
            } else {
                System.out.println("Validar email");
                jtfSite.setEnabled(true);
                jtfSite.requestFocus();
            }

        }

    }//GEN-LAST:event_jtfEmailKeyPressed


    private void jtfCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCpfKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {

            cpf = jtfCpf.getText();
            cpf = cpf.replace(".", "");
            cpf = cpf.replace("-", "");
            
            if (ValidaCNP.isValidCPF(cpf) == false) {
                JOptionPane.showMessageDialog(null, "CPF inválido");
                return;
            }

            jcbEstadoCivil.setEnabled(true);
            jcbEstadoCivil.requestFocus();

        }
    }//GEN-LAST:event_jtfCpfKeyPressed

    private void jcbEstadoCivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbEstadoCivilKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {

            jcbSexo.setEnabled(true);
            jcbSexo.requestFocus();

        }
    }//GEN-LAST:event_jcbEstadoCivilKeyPressed

    private void jtfRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRGKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {

            jtfOrgaoRg.setEnabled(true);
            jtfOrgaoRg.requestFocus();

        }
    }//GEN-LAST:event_jtfRGKeyPressed

    private void jtfOrgaoRgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfOrgaoRgKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {

       //     jftfDataEmissaoRg.setEnabled(true);
            //     jftfDataEmissaoRg.requestFocus();
            jftfDt_EmissaoRG.setEnabled(true);
            jftfDt_EmissaoRG.requestFocus();

        }

    }//GEN-LAST:event_jtfOrgaoRgKeyPressed

    private void jrbJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbJuridicoActionPerformed
        // TODO add your handling code here:

      
        jTabbedPane1.setEnabledAt(1, false);
        jpanelPessoaFisica.setVisible(false);
        jPanelLogin.setVisible(true);
        jLabelNome.setText("NOME FANTASIA");
        jtfNome.requestFocus();
      //  jPanelPessoaJuridica.setSize(300, 300);
        // jPanelPessoaJuridica.set

    }//GEN-LAST:event_jrbJuridicoActionPerformed

    private void jrbFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFisicaActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setEnabledAt(2, false);
        jPanelLogin.setVisible(false);
        jpanelPessoaFisica.setVisible(true);
        jLabelNome.setText("NOME");
        if (operacao == "salvar") {
            jtfNome.requestFocus();
        }
    }//GEN-LAST:event_jrbFisicaActionPerformed

    private void jcbSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbSexoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSexoFocusLost

    private void jcbSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbSexoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {

            jtfRG.setEnabled(true);
            jtfRG.requestFocus();
        }
    }//GEN-LAST:event_jcbSexoKeyPressed

    private void jbtAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAdicionarEnderecoActionPerformed
        enderecoView = new EnderecoView(new java.awt.Frame(), true);
        enderecoView.jtfLogradouro.setEnabled(true);
        enderecoView.setFormulario("colaborador");
        if (operacao == "alterar"){
           enderecoView.setPessoaId(Long.parseLong(jtfCodigo.getText()));
           enderecoView.setOperacao(operacao);
        }
        
      //  enderecoView.setSize(600, 354);
        enderecoView.setTitle("Cadastro de Endereco de Cliente");
        enderecoView.setLocationRelativeTo(null); // centraliza a tela 
        enderecoView.setVisible(true);       
    }//GEN-LAST:event_jbtAdicionarEnderecoActionPerformed

    private void jTableEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnderecoMouseClicked


    }//GEN-LAST:event_jTableEnderecoMouseClicked

    private void jbtExcluirEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirEnderecoActionPerformed
        try {
            Long id = (Long) jTableEndereco.getValueAt(jTableEndereco.getSelectedRow(), 10);
            if (id > 0) {
                PessoaEnderecoDAO daoEndereco = new PessoaEnderecoDAO();
                daoEndereco.remover(id);
                ((DefaultTableModel) jTableEndereco.getModel()).removeRow(jTableEndereco.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Endereço Excluído com Sucesso !!!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Excluir Endereço, Click no Botão Salvar e tente novamente.");
            //ex.printStackTrace();
        }


    }//GEN-LAST:event_jbtExcluirEnderecoActionPerformed

    private void jtfPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaClienteActionPerformed

    private void jtfPesquisaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaClienteKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTable1.requestFocus();
        } else if (evt.getKeyCode() == evt.VK_TAB) {
            jbtNovo.requestFocus();
        }


    }//GEN-LAST:event_jtfPesquisaClienteKeyPressed

    private void jbtAdicionaContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAdicionaContatoActionPerformed
        // TODO add your handling code here:
//        contatoView.setSize(404, 262);
//        contatoView.setTitle("Cadastro de Contato do Cliente");
//        contatoView.setLocationRelativeTo(null); // centraliza a tela 
//        contatoView.setVisible(true);
        
        
        
        
        
        contatoView = new ContatoView(new java.awt.Frame(), true);
      //  contatoView.setSize(404, 262);
        contatoView.setTitle("Cadastro de Contato do Cliente");
        contatoView.setLocationRelativeTo(null); // centraliza a tela                            
        contatoView.setFormulario("colaborador");
        if (operacao == "alterar"){
           contatoView.setPessoaId(Long.parseLong(jtfCodigo.getText()));
           contatoView.setOperacao(operacao);
        }
        contatoView.setVisible(true);
        


    }//GEN-LAST:event_jbtAdicionaContatoActionPerformed

    private void jbtAdicionarEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtAdicionarEnderecoKeyPressed
        // TODO add your handling code here:
//        if (evt.getKeyCode() == evt.VK_ENTER){
//            jbtAdicionarEnderecoActionPerformed(null);
//        }

        // 
    }//GEN-LAST:event_jbtAdicionarEnderecoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setEnabledAt(4, true);
        jTabbedPane1.setSelectedIndex(4);
        jbtAdicionaContato.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        operacao = "alterar";
        habilitar(true);
        limpar();
        PessoaDAO pessoaDAO = new PessoaDAO();
        //Instancia pessoa fisica.
        PessoaFisica pf = new PessoaFisica();
        PessoaFisicaDAO pfDAO = new PessoaFisicaDAO();
        
        pessoa = new Pessoa() {};
        //Código de pessoa.
        Long id = (Long) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        jTabbedPane1.setSelectedIndex(0);
        enderecoView = new EnderecoView(new java.awt.Frame(), true);
        contatoView = new ContatoView(new java.awt.Frame(), true);
        //Se for Pessoa Física faça isso abaixo;
        pessoa = pessoaDAO.pessoa(id);
        pf = pfDAO.pessoaFisica(id);
        //Desabilitar Panel de Pessoa Juridica
       // jPanelLogin.setVisible(false);
        jrbFisica.setSelected(true);
        jtfCodigo.setEditable(false);
        jtfCodigo.setFocusable(false);
        jtfSenha.setText(pessoa.getColaborad().getSenha());
        if (pessoa.getColaborad().getUltimo_acesso() == null)
            jtfUltimoAcesso.setText("");
        else
           jtfUltimoAcesso.setText(sdf.format(pessoa.getColaborad().getUltimo_acesso()));

        jcbTipoUsuario.setSelectedItem(pessoa.getColaborad().getTipo_usuario());
      //  jcbEstadoCivil.setSelectedItem(colaborador.getEstado_civil().toString());
        jcbEstadoCivil.setSelectedItem(pf.getEstado_civil());

        if (pf.getSexo().equals("M")) {
            jcbSexo.setSelectedIndex(0);
        }else
           if (pf.getSexo().equals("F")) {
               jcbSexo.setSelectedIndex(1);
           }

        jtfCodigo.setText((pessoa.getId().toString()));

       

        
       // if (pf.getColaborad().getDt_cadastro(pf.getColaborad().getDt_cadastro()));
       
       //String dt_cad = sdfdt_cad.format(cliente.getCli().getDataCadastro());
       // System.out.println("Data Cadastro Colaborador ="+ pf.getColaborad().getDt_cadastro());
        if (pessoa.getColaborad().getDt_cadastro() == null)
            jftfDataCadastro.setText("");
        else{
            String dt_cad = sdf.format(pessoa.getColaborad().getDt_cadastro());
            jftfDataCadastro.setText(dt_cad);
        }
        
        
        jtfNome.setText(pf.getNome());
        jtfEmail.setText(pf.getEmail());
        jtfSite.setText(pf.getSite());
        jtfCpf.setText(pf.getCpf());
        jtfRG.setText(pf.getRg());
        jtfOrgaoRg.setText(pf.getOrgao_rg());
        //Data Emissao RG
        if (pf.getData_emissao() == null) {
           jftfDt_EmissaoRG.setText("");
        }else{ 
           String dt_emissaoRG = sdf.format(pf.getData_emissao()); // Converte data para string.
           jftfDt_EmissaoRG.setText(dt_emissaoRG);
        }          
        if (pessoa.getColaborad().getDt_admissao() == null)
            jtfDt_Admissao.setText("");
        else{
           String dt_admissao = sdf.format(pessoa.getColaborad().getDt_admissao());
           jtfDt_Admissao.setText(dt_admissao);
        }  
        if (pessoa.getColaborad().getDt_demissao() == null)
            jtfDt_Demissao.setText("");
        else{
            String dt_demissao = sdf.format(pessoa.getColaborad().getDt_demissao());
            jtfDt_Demissao.setText(dt_demissao);        
        }             
        jtfLogin.setText(pessoa.getColaborad().getLogin());  
        

        List<PessoaEndereco> listaEndereco = new ArrayList<PessoaEndereco>();
        listaEndereco = pfDAO.enderecos(id);
        DefaultTableModel amodel = (DefaultTableModel) jTableEndereco.getModel();
        amodel.setNumRows(0);
        for (PessoaEndereco endereco : listaEndereco) {
            amodel.addRow(new Object[]{endereco.getLogradouro(), endereco.getNumero(), endereco.getBairro(),
                endereco.getCidade(), endereco.getUf(), endereco.getCep(), endereco.getPrincipal(),
                endereco.getCorrespondencia(), endereco.getEntrega(), endereco.getCobranca(), endereco.getId()});
        }

        List<PessoaContato> listaContato = new ArrayList<PessoaContato>();
        listaContato = pfDAO.contatos(id);
        DefaultTableModel amodel1 = (DefaultTableModel) jTableContato.getModel();
        amodel1.setNumRows(0);
        for (PessoaContato contato : listaContato) {
            amodel1.addRow(new Object[]{contato.getDescricao(), contato.getDdd(), contato.getNumero(), contato.getId()});
        }
        jbtSalvar.setEnabled(true);
        jTabbedPane1.setEnabledAt(1, true);
        jpanelPessoaFisica.setEnabled(true);
        jTabbedPane1.setEnabledAt(2, true);
           // jTabbedPane1.setVisible(false);

        jbtSalvar.setEnabled(true);
        jbtNovo.setEnabled(false);
        jbtCancelar.setEnabled(true);
        jbtExcluir.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jftfDt_EmissaoRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftfDt_EmissaoRGKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTabbedPane1.setEnabledAt(2, true);
            jPanelLogin.setVisible(true);
            jTabbedPane1.setSelectedIndex(2);
            jPanelLogin.setEnabled(true);
            jtfLogin.setEnabled(true);
            jtfLogin.requestFocus();
        }
    }//GEN-LAST:event_jftfDt_EmissaoRGKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Long id = (Long) jTableContato.getValueAt(jTableContato.getSelectedRow(), 3);
            if (id > 0) {
                PessoaContatoDAO daoContato = new PessoaContatoDAO();
                daoContato.remover(id);
                ((DefaultTableModel) jTableContato.getModel()).removeRow(jTableContato.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Contato Excluído com Sucesso !!!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Excluir Contato, click no Botão Salvar e Tente novamente.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfSiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (jrbFisica.isSelected()) {
                jTabbedPane1.setEnabledAt(1, true);
                jTabbedPane1.setEnabledAt(2, false);
                jTabbedPane1.setSelectedIndex(1);
                jtfCpf.setEnabled(true);
                jtfCpf.requestFocus();
            } else {
                jTabbedPane1.setEnabledAt(2, true);
                jTabbedPane1.setEnabledAt(1, false);
                jTabbedPane1.setSelectedIndex(2);
                jtfLogin.setEnabled(true);
                jtfLogin.requestFocus();
            }

        }
    }//GEN-LAST:event_jtfSiteKeyPressed

    private void jtfSiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSiteFocusLost
        // TODO add your handling code here:
        jtfSite.setText(jtfSite.getText().toLowerCase());
    }//GEN-LAST:event_jtfSiteFocusLost

    private void jtfLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLoginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            jtfDt_Admissao.setEnabled(true);
            jtfDt_Admissao.requestFocus();
        }
    }//GEN-LAST:event_jtfLoginKeyPressed

    private void jtfLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfLoginFocusLost
         jtfLogin.setText(RemoverAcentosString.semAcento(jtfLogin.getText().toUpperCase()));
    }//GEN-LAST:event_jtfLoginFocusLost

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
           // jTable1MouseClicked(null);
          //  jTable1.a
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jtfDt_AdmissaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDt_AdmissaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            jtfDt_Demissao.setEnabled(true);
            jtfDt_Demissao.requestFocus();
            
            
        }
    }//GEN-LAST:event_jtfDt_AdmissaoKeyPressed

    private void jtfDt_DemissaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDt_DemissaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            jcbTipoUsuario.setEnabled(true);
            jcbTipoUsuario.requestFocus();
        }
    }//GEN-LAST:event_jtfDt_DemissaoKeyPressed

    private void jcbTipoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbTipoUsuarioKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            jtfSenha.setEnabled(true);
            jtfSenha.requestFocus();
        }
    }//GEN-LAST:event_jcbTipoUsuarioKeyPressed

    private void jtfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSenhaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            jtfRedSenha.setEnabled(true);
            jtfRedSenha.requestFocus();
        }
    }//GEN-LAST:event_jtfSenhaKeyPressed

    private void jtfRedSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRedSenhaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            if (jtfSenha.getText().equals(jtfRedSenha.getText())){
               jTabbedPane1.setEnabledAt(3, true);
               jTabbedPane1.setSelectedIndex(3);
               jbtAdicionaContato.setEnabled(true);
               jbtAdicionarEndereco.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null, "As senha não são iguais. Digite novamente.");
                jtfRedSenha.requestFocus();
            }
                
        }
    }//GEN-LAST:event_jtfRedSenhaKeyPressed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        
//        Long idColaborador = Long.parseLong(jtfCodigo.getText());
//        
//        if (jrbFisica.isSelected()){
//           PessoaFisicaDAO daoPessoa = new PessoaFisicaDAO();
//           PessoaFisica p = daoPessoa.pessoaFisica(idColaborador);
//           
//           daoPessoa.excluir(idColaborador);
//           
//           JOptionPane.showMessageDialog(null, "Colaborador excluido com sucesso !!!");
//        }
        
        
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtNovoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtNovoActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtNovoKeyPressed

    private void jbtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtCancelarKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
              jbtCancelarActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtCancelarKeyPressed

    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtSalvarActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jbtSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSairKeyPressed

         if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
               jbtSairActionPerformed(null);
        }  
    }//GEN-LAST:event_jbtSairKeyPressed

    public void habilitar(boolean habilita) {
       
        jtfNome.setEnabled(habilita);
        jftfDataCadastro.setEditable(habilita);
        jTabbedPane1.setEnabledAt(0, habilita);
        jTabbedPane1.setEnabledAt(1, habilita);
        jTabbedPane1.setEnabledAt(2, habilita);
        jTabbedPane1.setEnabledAt(3, habilita);
        jTabbedPane1.setEnabledAt(4, habilita);
//        jTabbedPane1.setEnabledAt(5, habilita);
        jrbFisica.setEnabled(habilita);
        jrbJuridico.setEnabled(habilita);

        jtfRG.setEnabled(habilita);
        jtfCpf.setEnabled(habilita);
        jtfEmail.setEnabled(habilita);
        jtfSite.setEnabled(habilita);
        jtfOrgaoRg.setEnabled(habilita);

        jcbEstadoCivil.setEnabled(habilita);
        jcbSexo.setEnabled(habilita);
//        jftfDataEmissaoRg.setEnabled(habilita);
        jtfPesquisaCliente.setEnabled(habilita);
        jtfCodigo.setEnabled(habilita);
        jftfDataCadastro.setEnabled(habilita);
        jftfDt_EmissaoRG.setEnabled(habilita);

        jtfSite.setEnabled(habilita);
        jtfSenha.setEnabled(habilita);
        jtfLogin.setEnabled(habilita);
        jcbTipoUsuario.setEnabled(habilita);
        jtfDt_Admissao.setEnabled(habilita);
        jtfDt_Demissao.setEnabled(habilita);
    }

    public void salvar() throws ParseException {

        PessoaFisica pf = new PessoaFisica();

        pf.setTipo("F");
        pf.setColaborador("S");
        if (!jtfNome.getText().equals("")) {
            pf.setNome(jtfNome.getText());
        } else {
            JOptionPane.showMessageDialog(null, "O campo Nome não pode ser vazio!!!");
            jTabbedPane1.setSelectedIndex(0);
            jtfNome.requestFocus();
        }
        if (!jtfEmail.getText().equals("")) {
            pf.setEmail(jtfEmail.getText());
        } else {
            pf.setEmail("");
        }
        if (!jtfSite.getText().equals("")) {
            pf.setSite(jtfSite.getText());
        } else {
            pf.setSite("");
        }
        if (!jtfCpf.getText().equals("")) {
            pf.setCpf(cpf);
        } else {
            pf.setCpf("");
        }
//        pf.setId_estadocivil(1);
        if (jcbSexo.getSelectedIndex() == 0) {
            pf.setSexo("M");
        } else {
            pf.setSexo("F");
        }
        if (!jtfRG.getText().equals("")) {
            pf.setRg(jtfRG.getText());
        } else {
            pf.setRg("");
        }
        if (!jtfOrgaoRg.getText().equals("")) {
            pf.setOrgao_rg(jtfOrgaoRg.getText());
        } else {
            pf.setOrgao_rg("");
        }
        // System.out.println("Valor do combobox =" + jcbEstadoCivil.getSelectedIndex());
        switch (jcbEstadoCivil.getSelectedIndex()) {
            case 0: {
                pf.setEstado_civil(EstadoCivil.SOLTEIRO);
                break;
            }
            case 1: {
                pf.setEstado_civil(EstadoCivil.CASADO);
                break;
            }
            case 2: {
                pf.setEstado_civil(EstadoCivil.UNIAO_ESTAVEL);
                break;
            }
            case 3: {
                pf.setEstado_civil(EstadoCivil.AMASIADO);
            }
            case 4: {
                pf.setEstado_civil(EstadoCivil.VIUVO);
            }
        }
        if (jftfDt_EmissaoRG.getText() == null || jftfDt_EmissaoRG.getText().equals("")) {
            
            jftfDt_EmissaoRG.setText(null);
        } else {
            try {
                pf.setData_emissao((sdf.parse(jftfDt_EmissaoRG.getText())));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Data Inválida oi");
            }
        }

        Colaborador colaborador = new Colaborador();

        try {
            if (!jtfDt_Admissao.getText().equals("")) {
                colaborador.setDt_admissao(new Date(sdf.parse(jtfDt_Admissao.getText()).getTime()));
            }else{
                colaborador.setDt_admissao(y);
            }
            if (!jtfDt_Demissao.getText().equals("")) {
                colaborador.setDt_demissao(new Date(sdf.parse(jtfDt_Demissao.getText()).getTime()));
            } else{
                colaborador.setDt_demissao(null);
            }           
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Data inválida.");
        }
        if (!jtfLogin.getText().equals("")){
            colaborador.setLogin(jtfLogin.getText());
        //colaborador.setSenha(cnpj);
            colaborador.setSenha(jtfSenha.getText());
                        
        }else 
            if (operacao.equals("salvar")){
               JOptionPane.showMessageDialog(null, "Preencha o campo de Login e Senha, do Colaborador para o cadastro ser Finalizado. ");
               jTabbedPane1.setEnabledAt(0, true);
               jTabbedPane1.setSelectedIndex(0);
               jtfNome.requestFocus();
               return;
            }
        if (jcbTipoUsuario.getSelectedIndex() < 0)
            jcbTipoUsuario.setSelectedItem("COLABORADOR");
        
        colaborador.setTipo_usuario((String) jcbTipoUsuario.getSelectedItem());
        //Adicionando Endereco 
        List<PessoaEndereco> listaEndereco = new ArrayList<PessoaEndereco>();
        if (!jTableEndereco.getSize().equals(0)) {

            for (int i = 0; i < jTableEndereco.getRowCount(); i++) {

                PessoaEndereco pEndereco = new PessoaEndereco();

                pEndereco.setLogradouro((String) jTableEndereco.getValueAt(i, 0));
                pEndereco.setNumero((String) jTableEndereco.getValueAt(i, 1));
                pEndereco.setBairro((String) jTableEndereco.getValueAt(i, 2));
                pEndereco.setCidade((String) jTableEndereco.getValueAt(i, 3));
                pEndereco.setUf((String) jTableEndereco.getValueAt(i, 4));
                pEndereco.setCep((String) jTableEndereco.getValueAt(i, 5));
                
                Boolean principal = (Boolean) (jTableEndereco.getValueAt(i, 6));
                Boolean correspondencia = (Boolean) (jTableEndereco.getValueAt(i, 7));
                Boolean entrega = (Boolean) (jTableEndereco.getValueAt(i, 8));
                Boolean cobranca = (Boolean) (jTableEndereco.getValueAt(i, 9));

                Long id = (Long) (jTableEndereco.getValueAt(i, 10));

                if (id != 0) {
                    //String idStr = String.valueOf(id);
                    pEndereco.setId(id);
                } else {
                    pEndereco.setId(null);
                }

                listaEndereco.add(new PessoaEndereco(pEndereco.getLogradouro(), pEndereco.getNumero(), null, pEndereco.getBairro(), pEndereco.getCidade(),
                        pEndereco.getCep(), pEndereco.getUf(), entrega, cobranca, principal, correspondencia, pEndereco.getId()));
            }

            //Adicionando Contato do Cliente
            List<PessoaContato> listaContato = new ArrayList<PessoaContato>();
            if (!jTableContato.getSize().equals(0)) {
                for (int i = 0; i < jTableContato.getRowCount(); i++) {
                    PessoaContato pContato = new PessoaContato();
                    pContato.setDescricao((String) jTableContato.getValueAt(i, 0));
                    pContato.setDdd((String) jTableContato.getValueAt(i, 1));
                    pContato.setNumero((String) jTableContato.getValueAt(i, 2));
                    pContato.setId((Long) jTableContato.getValueAt(i, 3));

                    
                    if (pContato.getId() == 0) {
                        pContato.setId(null);
                    }
                    // System.out.println("Lista de Contato :" + pContato.getDescricao() + ", " + pContato.getDdd() + ", " + pContato.getNumero());
                    listaContato.add(new PessoaContato(pContato.getId(), pContato.getDescricao(), pContato.getDdd(), pContato.getNumero()));
                }

            } else {
                listaContato = null;
            }

            // ClienteDAO daoCli = new ClienteDAO();
            ColaboradorDAO daoColab = new ColaboradorDAO();
            if (operacao == "salvar") {
                try {
                    
                    colaborador.setDt_cadastro(y);
                    
                    pf.setColaborad(colaborador);

                    daoColab.salvar(pf, listaEndereco, listaContato);
                    JOptionPane.showMessageDialog(null, "Colaborador salvo com sucesso !!!");
                    jbtCancelarActionPerformed(null);
                    carregaTable();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Problemas ao Salvar Colaborador:" + ex.getMessage());
                    ex.printStackTrace();
                }
            } else if (operacao == "alterar") {
                jtfPesquisaCliente.setText("");
                pf.setId(Long.parseLong(jtfCodigo.getText()));
                colaborador.setId(pessoa.getColaborad().getId());
                colaborador.setDt_cadastro(sdf.parse(jftfDataCadastro.getText()));
                daoColab.alterar(pf, colaborador, listaEndereco, listaContato);
                JOptionPane.showMessageDialog(null, "Colaborador Alterado com Sucesso !!!");
            }

        }
    }

    
    
    
    public void limpar() {
        jtfCodigo.setText("");
        jtfNome.setText("");
        jftfDataCadastro.setText("");
        //      jcbTipoCliente.setSelectedIndex(-1);
        jtfEmail.setText("");
        jtfSite.setText("");
        jtfCpf.setText("");
        //  jtfPesquisaCliente.setText("");
        jtfRG.setText("");
        jtfCpf.setText("");
        jtfOrgaoRg.setText("");
        jftfDt_EmissaoRG.setText("");
//        jftfDataEmissaoRg.setText("");
        jcbEstadoCivil.setSelectedIndex(0);
        jcbSexo.setSelectedIndex(0);
       
        jtfLogin.setText("");
       // jtfPesquisaCliente.setText("");

   //     jtfEndereco.setText("");
        //     jtfBairro.setText("");
        //     jtfCidade.setText("");
        //     jcbEstado.setSelectedItem(null);
        //     jtfTelefone.setText("");
        //     jtfNascimento.setText("");
        //     jtfDesde.setText("");
        //     jtfEmpresa.setText("");
        //     jtfReferencia.setText("");
        //     jtfFoneRef.setText("");
        //     
    }

    public JTextField DefinirTiposCaracteresETamanho(int tamanho, String caracteres) {
        try {
            //defino a variável que vai guardar a quantidade de caracteres
            String quantidade = "";

		//defino um método de repetição para repetir o numero de
            //vezes  do tamanho
            for (int i = 0; i < tamanho; i++) {
                // defino asterisco para aceitar qualquer coisa e crio a máscara
                quantidade = quantidade + "*";
            }
		//  **********...   de acordo com o tamanho informado
            // defino que a mascara possui essa
            //quantidade de elementos que foi informado em tamanho e
            // foi colocada com * dentro de quantidade
            javax.swing.text.MaskFormatter nome = new javax.swing.text.MaskFormatter(quantidade);

		//defino que o parâmetro caracter recebido pelo
            //método contém os caracteres válidos 
            nome.setValidCharacters(caracteres);

            //retorno a mascara que foi criada  
            return new javax.swing.JFormattedTextField(nome);
        }// fim do try
        catch (Exception e) {
            //mensagem se acontecer erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
            //retorno um campo de texto comum  
            return new JTextField();
        }//fim do catch
    }
    //Não estou usando
    public MaskFormatter Mascara(String Mascara){
        MaskFormatter F_Mascara = new MaskFormatter();
        try{
            F_Mascara.setMask(Mascara); //Atribui a mascara
            F_Mascara.setPlaceholderCharacter(' '); //Caracter para preencimento 
        }
        catch (Exception excecao) {
            excecao.printStackTrace();
        } 
        return F_Mascara;
    }
    private void carregaTable(){
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
        amodel.setNumRows(0);
        ColaboradorDAO colDAO = new ColaboradorDAO();
        //PessoaDAO pessoaDAO = new PessoaDAO();
        try{
           listaColaborador = null;        
           listaColaborador = colDAO.getListColab();        
            
           for (Colaborador colab : listaColaborador){
               amodel.addRow(new Object[]{colab.getPessoa().getId(), colab.getPessoa().getNome()});            
           }
        }catch (Exception ex){
             JOptionPane.showMessageDialog(null, "Problemas ao Carregar Tabela de Colaboradores"+ex.getMessage());
             ex.printStackTrace();
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel cpfLabel1;
    private javax.swing.JLabel cpfLabel2;
    private javax.swing.JLabel cpfLabel5;
    private javax.swing.JLabel cpfLabel6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTableContato;
    public static javax.swing.JTable jTableEndereco;
    private javax.swing.JButton jbtAdicionaContato;
    private javax.swing.JButton jbtAdicionarEndereco;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtExcluirEndereco;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox jcbEstadoCivil;
    private javax.swing.JComboBox jcbSexo;
    private javax.swing.JComboBox jcbTipoUsuario;
    private javax.swing.JFormattedTextField jftfDataCadastro;
    private javax.swing.JFormattedTextField jftfDt_EmissaoRG;
    private javax.swing.JPanel jpanelPessoaFisi;
    private javax.swing.JPanel jpanelPessoaFisica;
    public static javax.swing.JRadioButton jrbFisica;
    public static javax.swing.JRadioButton jrbJuridico;
    public static javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfDt_Admissao;
    private javax.swing.JTextField jtfDt_Demissao;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfOrgaoRg;
    public static javax.swing.JTextField jtfPesquisaCliente;
    private javax.swing.JTextField jtfRG;
    private javax.swing.JPasswordField jtfRedSenha;
    private javax.swing.JPasswordField jtfSenha;
    private javax.swing.JTextField jtfSite;
    private javax.swing.JTextField jtfUltimoAcesso;
    private javax.swing.JLabel orgaoRgLabel;
    private javax.swing.JLabel orgaoRgLabel1;
    private javax.swing.JLabel rgLabel;
    private converter.RowSorterToStringConverter rowSorterToStringConverter1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
